module.exports = {
  listBox: {backgroundColor: '#fff', color: '#888', borderRadius: 10},
  listTitle: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  listText: {
    fontSize: 20,
    paddingTop: 5,
    paddingRight: 0,
    paddingBottom: 5,
    paddingLeft: 0,
    fontWeight: 'bold',
    color: '#222222',
    lineHeight: 38,
  },
  list: {height: 100, overflow: 'hidden', position: 'relative'},
  listWrap: {position: 'absolute'},
  free: {backgroundColor: '#f8f8f8'},
  buy: {backgroundColor: '#f1fcfa'},
  listItem: {
    height: 32,
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
    flexDirection: 'row',
    alignItems: 'center',
    fontSize: 11,
    borderRadius: 16,
    color: '#222222',
    marginBottom: 16,
  },
  avatar: {width: 24, height: 24, borderRadius: 12, flexShrink: 0},
  desc: {marginLeft: 10, lineHeight: 20},
  noInfo: {paddingTop: 20, paddingRight: 0, paddingBottom: 20, paddingLeft: 0},
  noInfoText: {textAlign: 'center', fontSize: 12, color: '#222222'},
}
