module.exports = {
  invitePage: {backgroundColor: '#f5f5f5', height: '100%'},
  sharePicture: {height: 640},
  tips: {textAlign: 'center', color: '#9E9E9E'},
  poster: {
    backgroundColor: '#fff',
    borderRadius: 10,
    position: 'relative',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
  },
  txt: {textAlign: 'center', fontWeight: '500', color: '#3A3A3A', fontSize: 16},
  image: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
    width: '100%',
  },
  tagImage: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
    width: '100%',
    position: 'absolute',
    left: 10,
    top: 10,
  },
  nickname: {color: '#9E9E9E'},
  slogan: {marginTop: 10},
  bottom: {justifyContent: 'space-between', flexDirection: 'row'},
  left: {marginTop: 20, marginLeft: 10, flexDirection: 'row'},
  mini: {fontSize: 10, color: '#9E9E9E', textAlign: 'center', marginTop: -4, marginBottom: 10},
}
