module.exports = {
  productList: {backgroundColor: '#f7f7f7'},
  item: {borderRadius: 10, width: '50%', paddingTop: 5, paddingBottom: 5},
  inner: {borderRadius: 10, backgroundColor: 'white'},
  image: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
    width: 60,
    height: 60,
  },
  title: {
    width: '100%',
    fontSize: 14,
    fontWeight: '400',
    color: '#333333',
    lineHeight: 17,
    marginTop: 4,
    marginBottom: 4,
  },
  tag: {
    maxWidth: 60,
    backgroundColor: '#FF4A4A',
    color: '#fff',
    alignSelf: 'flex-start',
    fontSize: 10,
    paddingTop: 2,
    paddingRight: 6,
    paddingBottom: 2,
    paddingLeft: 6,
    marginTop: 0,
    marginRight: 2,
    marginBottom: 0,
    marginLeft: 2,
    borderRadius: 2,
    overflow: 'hidden',
  },
  desc: {fontSize: 14, fontWeight: '400', color: '#D0B98D', lineHeight: 20},
  sales: {fontSize: 12, fontWeight: '400', color: '#adadad', lineHeight: 16, marginTop: 2},
  content: {paddingTop: 8, paddingRight: 10, paddingBottom: 8, paddingLeft: 10},
  bottom: {marginTop: 10, flexDirection: 'row', overflow: 'hidden'},
  yuan: {color: '#E73A32', fontSize: 12, paddingTop: 6},
  price: {color: '#E73A32', fontWeight: 'bold', fontSize: 16},
  preTagWrapper: {flexDirection: 'row', position: 'relative', bottom: -14, height: 16},
  preTag: {
    color: 'white',
    height: 16,
    borderRadius: 2,
    fontSize: 12,
    lineHeight: 14,
    paddingTop: 1,
    paddingRight: 2,
    paddingBottom: 1,
    paddingLeft: 2,
  },
  originalPrice: {
    marginTop: 4,
    marginLeft: 8,
    textDecorationLine: 'line-through',
    textDecorationColor: '#9E9E9E',
    textDecorationStyle: 'solid',
    color: '#9E9E9E',
    fontSize: 12,
  },
  suffixTag: {
    borderWidth: 1,
    borderColor: '#E73A32',
    borderStyle: 'solid',
    color: '#E73A32',
    backgroundColor: 'white',
    height: 16,
    borderRadius: 2,
    fontSize: 12,
    lineHeight: 12,
    paddingTop: 1,
    paddingRight: 2,
    paddingBottom: 1,
    paddingLeft: 2,
    marginLeft: 4,
  },
  footer: {marginTop: 6},
  comment: {color: '#9E9E9E'},
}
