module.exports = {
  waterFallWrap: {display: 'flex', paddingRight: 8, flexDirection: 'row'},
  icons: {
    zIndex: 0,
    position: 'absolute',
    top: 10,
    right: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 20,
    marginRight: 10,
    backgroundColor: '#FFFFFF',
    width: 34,
    height: 34,
    borderRadius: 8,
  },
  leftWrap: {paddingLeft: 8, width: '50%'},
  rightWrap: {paddingLeft: 8, width: '50%'},
  editBtn: {
    width: 140,
    position: 'absolute',
    paddingTop: 0,
    paddingRight: 20,
    paddingBottom: 0,
    paddingLeft: 20,
    bottom: 20,
    backgroundColor: '#ff9100',
    borderRadius: 16,
  },
  markDiv: {
    backgroundColor: '#f7f7f7',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 15,
    color: '#9E9E9E',
  },
  markImg: {height: 40, width: '100%'},
  imgWrap: {display: 'flex', alignItems: 'center', overflow: 'hidden', marginBottom: 8},
  mainImage: {width: '100%'},
}
