module.exports = {
  shopWrap: {
    paddingTop: 0,
    paddingRight: 20,
    paddingBottom: 0,
    paddingLeft: 20,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shoppingCartItem: {borderRadius: 10, paddingTop: 14, paddingBottom: 14, marginBottom: -1},
  right: {marginTop: 5, marginLeft: 10},
  title: {width: '100%', fontSize: 14, fontWeight: '400', color: '#333333', lineHeight: 17},
  storeTitle: {flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', paddingRight: 20},
  recommend: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 17,
    marginTop: 60,
    marginRight: 0,
    marginBottom: 30,
    marginLeft: 0,
  },
  look: {fontSize: 12, fontWeight: '400', color: '#3A3A3A', lineHeight: 17},
  storeNickname: {
    color: '#3A3A3A',
    marginTop: 4,
    marginLeft: 10,
    fontSize: 16,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
  },
  skuBorder: {borderTopWidth: 1, borderTopColor: '#eee'},
  skuItem: {
    marginTop: 5,
    marginRight: 5,
    marginBottom: 5,
    marginLeft: 5,
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingTop: 18,
    paddingRight: 14,
    paddingBottom: 18,
    paddingLeft: 14,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  eachImage: {
    borderRadius: 6,
    width: 90,
    height: 90,
    marginTop: 0,
    marginRight: 10,
    marginBottom: 0,
    marginLeft: 10,
    backgroundColor: '#f7f7f7',
  },
  skuContent: {width: '55%'},
  skuTitle: {width: '100%', color: '#303133', fontSize: 16, lineHeight: 16},
  skuSpecBox: {
    marginTop: 8,
    borderRadius: 20,
    backgroundColor: '#f9f6f9',
    paddingTop: 5,
    paddingRight: 10,
    paddingBottom: 5,
    paddingLeft: 10,
  },
  skuSpec: {
    color: '#747474',
    fontSize: 12,
    backgroundColor: '#f4f4f4',
    opacity: 0.8,
    borderRadius: 17,
    lineHeight: 20,
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    overflow: 'hidden',
    maxWidth: '90%',
    height: 20,
    marginTop: 8,
  },
  bottom: {marginTop: 8, flexDirection: 'row', justifyContent: 'space-between'},
  yuan: {color: '#FA632C', fontSize: 12, paddingTop: 5},
  price: {color: '#FA632C', fontWeight: 'bold', fontSize: 16},
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    left: 0,
    paddingTop: 16,
    paddingRight: 14,
    paddingBottom: 16,
    paddingLeft: 14,
    flexDirection: 'row',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectAll: {color: '#ABAAB0', fontSize: 16, marginLeft: 10},
  totalBox: {flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end'},
  total: {textAlign: 'right', fontSize: 12, fontWeight: 'bold', color: '#000000'},
  totalPrice: {fontSize: 16, fontWeight: 'bold', color: '#FA632C'},
  buttonText: {
    textAlign: 'center',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    lineHeight: 36,
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 16,
  },
  bottomTitle: {textAlign: 'right'},
  skuHiddenWrap: {
    marginTop: 34,
    backgroundColor: '#f7f7f7',
    width: 36,
    height: 20,
    borderRadius: 10,
    paddingTop: 4,
    paddingRight: 6,
    paddingBottom: 4,
    paddingLeft: 6,
  },
  skuHidden: {color: '#3A3A3A', fontSize: 12},
  delete: {color: '#E73A32', paddingRight: 10},
  bottomLeft: {height: 30, flexDirection: 'row'},
  bottomRight: {flexDirection: 'row'},
  bottomBtn: {borderRadius: 20, paddingTop: 10, paddingRight: 15, paddingBottom: 10, paddingLeft: 15},
  buttonDel: {borderWidth: 1, borderRadius: 18, marginLeft: 20},
  buttonDelText: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 16,
    lineHeight: 36,
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 16,
  },
}
