module.exports = {
  modalWrap: {paddingTop: 30, paddingRight: 20, paddingBottom: 0, paddingLeft: 20},
  title: {textAlign: 'center', fontSize: 18, fontWeight: '500'},
  homeAd: {
    position: 'absolute',
    zIndex: 1000,
    bottom: 100,
    width: 160,
    height: 40,
    backgroundColor: '#fe1433',
    borderRadius: 30,
  },
  homeAdText: {color: '#fff', textAlign: 'center', fontSize: 18, lineHeight: 40},
  tag: {
    height: 16,
    lineHeight: 16,
    backgroundColor: '#FF2A41',
    marginRight: 6,
    color: '#fff',
    fontSize: 10,
    paddingTop: 0,
    paddingRight: 3,
    paddingBottom: 0,
    paddingLeft: 3,
    fontWeight: '400',
    borderRadius: 2,
    overflow: 'hidden',
    marginTop: 5,
  },
  homeSafe: {backgroundColor: '#fff'},
  helpBox: {marginBottom: 20},
  helpLabel: {color: '#323233', fontSize: 14, lineHeight: 24},
  helpTittle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#202020',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingRight: 16,
    paddingBottom: 10,
    paddingLeft: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ebedf0',
  },
  helpList: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingRight: 16,
    paddingBottom: 10,
    paddingLeft: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ebedf0',
  },
  homeTitle: {fontSize: 20, fontWeight: 'bold', paddingTop: 30, paddingLeft: 20},
  homeImage: {width: 120, height: 20},
  desc: {marginTop: 2},
  articleTitle: {fontSize: 18, color: '#3A3A3A', fontWeight: '500', textAlign: 'center'},
  homePage: {backgroundColor: '#fff'},
  center: {textAlign: 'center'},
  input: {
    position: 'absolute',
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 16,
    width: '100%',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
  },
  icon: {lineHeight: 30, zIndex: 1, marginBottom: -30, marginLeft: 10, width: 30},
  carousel: {height: 150},
  txt: {color: 'white', textAlign: 'center', fontSize: 10, width: 40},
  hotSearch: {flexDirection: 'row'},
  label: {fontSize: 16, marginLeft: 14, marginTop: 4, marginBottom: 14, color: '#9E9E9E'},
  labelPrimary: {color: '#E73A32'},
  topWrap: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 24,
    borderBottomLeftRadius: 24,
  },
  middleBannerImage: {marginTop: 40, marginRight: 14, marginBottom: 14, marginLeft: 14, borderRadius: 10},
  bottomBanner: {marginTop: 20, marginRight: 14, marginBottom: 0, marginLeft: 14},
  bottomBannerImage: {height: 200, borderRadius: 20},
  selectionBrand: {
    marginTop: 14,
    marginRight: 14,
    marginBottom: 14,
    marginLeft: 14,
    backgroundColor: '#fff',
    borderRadius: 10,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  selectItem: {width: '50%'},
  selectImage: {height: 100, marginTop: 0, marginRight: 10, marginBottom: 14, marginLeft: 10},
  selectTitle: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
  },
  selectTitleUp: {color: 'black', fontSize: 16, marginRight: 6},
  selectDescription: {fontSize: 14, color: '#fff'},
  selectionLike: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row', marginBottom: 14},
  likeItem: {borderRadius: 10, paddingTop: 4, paddingRight: 6, paddingBottom: 4, paddingLeft: 6, marginLeft: 14},
  likeTitle: {textAlign: 'center', fontSize: 20, fontWeight: 'bold', color: '#fff'},
  likeSubTitle: {textAlign: 'center', color: '#fff', fontSize: 14, marginTop: 4, fontWeight: '500'},
  flashWrap: {
    backgroundColor: '#fff',
    marginTop: 10,
    marginRight: 10,
    marginBottom: 0,
    marginLeft: 10,
    borderRadius: 10,
  },
  packageWrap: {
    backgroundColor: '#fff',
    marginTop: 10,
    marginRight: 10,
    marginBottom: 30,
    marginLeft: 10,
    borderRadius: 10,
    paddingBottom: 10,
  },
  originalPrice: {
    fontSize: 14,
    textDecorationLine: 'line-through',
    textDecorationColor: '#9E9E9E',
    textDecorationStyle: 'solid',
    color: '#9E9E9E',
    width: 90,
    textAlign: 'center',
  },
  packageHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 14,
    paddingRight: 6,
    paddingBottom: 14,
    paddingLeft: 6,
  },
  flashItem: {width: 90, marginRight: 10, paddingTop: 0, paddingRight: 10, paddingBottom: 10, paddingLeft: 10},
  flashImage: {width: 90, height: 90},
  priceUnit: {fontSize: 12, color: '#222'},
  flashPrice: {width: 90, marginTop: 10, fontWeight: 'bold', color: '#222', textAlign: 'center'},
  countDownWrap: {marginLeft: 10},
  countDownLabel: {
    backgroundColor: '#E73A32',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 10,
  },
  countDownText: {
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
    lineHeight: 16,
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  area: {
    flexDirection: 'row',
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 16,
    justifyContent: 'space-between',
  },
  areaItem: {
    width: '31%',
    backgroundColor: '#fff',
    paddingTop: 20,
    paddingRight: 0,
    paddingBottom: 20,
    paddingLeft: 0,
    borderRadius: 8,
  },
  areaImage: {width: 36, height: 36, marginTop: 0, marginRight: 'auto', marginBottom: 0, marginLeft: 'auto'},
  areaLabel: {textAlign: 'center', marginTop: 10, fontWeight: 'bold', fontSize: 15},
  homeWrap: {
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 16,
    marginTop: 16,
    marginRight: 0,
    marginBottom: 16,
    marginLeft: 0,
  },
  homeWrapTitle: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  homeWrapTitleLeft: {fontSize: 18, fontWeight: 'bold', color: '#222'},
  homeWrapTitleRight: {fontSize: 14, color: '#abaab0'},
  homeWrapBox: {
    borderRadius: 12,
    marginRight: 20,
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    width: 140,
    height: 100,
  },
  playIcon: {width: 30, height: 30, marginTop: 'auto', marginRight: 'auto', marginBottom: 'auto', marginLeft: 'auto'},
  eachItem: {
    backgroundColor: '#fff',
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 20,
    paddingLeft: 20,
    marginTop: 20,
    marginRight: 20,
    marginBottom: 0,
    marginLeft: 20,
    borderRadius: 15,
  },
  image: {width: 80, borderRadius: 4, height: 80},
  right: {width: '100%', paddingTop: 0, paddingRight: 85, paddingBottom: 0, paddingLeft: 14},
  eachTitle: {width: '100%', color: '#3A3A3A', fontSize: 14, fontWeight: 'bold', minHeight: 40},
  spec: {color: '#FA632C', fontSize: 10, fontWeight: 'bold'},
  bottomArea: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  btn: {fontSize: 13, lineHeight: 32, fontWeight: 'bold', textAlign: 'center', color: '#fff'},
  homeNav: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 0,
    paddingRight: 6,
    paddingBottom: 0,
    paddingLeft: 6,
  },
  homeNavBox: {marginTop: 'auto', marginRight: 'auto', marginBottom: 'auto', marginLeft: 'auto'},
  homeIcon: {width: 18, height: 18, marginTop: 'auto', marginRight: 'auto', marginBottom: 'auto', marginLeft: 'auto'},
  menuNav: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
  },
  menuItem: {
    width: '23%',
    marginTop: 14,
    marginRight: '1%',
    marginBottom: '1%',
    marginLeft: '1%',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingTop: 14,
    paddingRight: 0,
    paddingBottom: 14,
    paddingLeft: 0,
  },
  menuImage: {backgroundColor: '#fff', width: 28, height: 28},
  menuLabel: {color: '#3A3A3A', marginTop: 6, fontSize: 14, fontWeight: '500'},
  topTittleBox: {marginTop: 12, flexDirection: 'row', alignItems: 'center'},
  topTittle: {marginLeft: 10},
  searchBox: {flexDirection: 'row', alignItems: 'center', width: '100%'},
  designBtn: {
    backgroundColor: '#F7F7F7',
    paddingTop: 5,
    paddingRight: 5,
    paddingBottom: 5,
    paddingLeft: 5,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 50,
  },
  searchWrap: {
    flexGrow: 1,
    backgroundColor: '#F7F7F7',
    borderRadius: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginRight: 12,
    paddingTop: 8,
    paddingRight: 4,
    paddingBottom: 8,
    paddingLeft: 4,
  },
  searchLeft: {flexDirection: 'row', alignItems: 'center'},
  searchRight: {width: '30%', flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end'},
  searchIconBox: {height: 30, paddingTop: 0, paddingRight: 10, paddingBottom: 0, paddingLeft: 10, borderRadius: 15},
  searchText: {lineHeight: 30, color: '#fff'},
  productBox: {marginTop: 10, flexDirection: 'row', justifyContent: 'space-around'},
  productItem: {width: 160, backgroundColor: '#fff'},
  productImage: {borderRadius: 4, width: 160, height: 160},
  bottomProduct: {marginTop: 6, paddingTop: 0, paddingRight: 12, paddingBottom: 0, paddingLeft: 12},
  productName: {color: '#333', fontSize: 14},
  normal: {fontSize: 14},
  menuBox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 12,
    paddingRight: 0,
    paddingBottom: 12,
    paddingLeft: 0,
  },
  menuItem1: {textAlign: 'center', width: '25%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center'},
  active: {textAlign: 'center', fontSize: 14, fontWeight: '400', lineHeight: 20, color: '#FF2A41'},
  defaults: {textAlign: 'center', fontSize: 14, fontWeight: '400', lineHeight: 20, color: '#898989'},
  contentBox: {paddingTop: 20, paddingRight: 0, paddingBottom: 20, paddingLeft: 0},
  content: {color: '#3A3A3A', fontSize: 16, lineHeight: 24},
  agreement: {color: '#90A96E'},
  btnBox: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 15,
    paddingRight: 0,
    paddingBottom: 15,
    paddingLeft: 0,
  },
  btnWrap: {width: '50%'},
  borderLeft: {borderLeftWidth: 1, borderLeftColor: '#eee'},
  modalBox: {
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    width: '100%',
    backgroundColor: '#fff',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  tabItem: {
    marginTop: 15,
    marginRight: 6,
    marginBottom: 0,
    marginLeft: 6,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#eee',
  },
  activeBox: {borderWidth: 1, borderColor: '#fe733b', backgroundColor: '#fff'},
  activeText: {color: '#fe733b'},
  advantage: {
    flexDirection: 'row',
    borderTop: '1px solid #eee',
    marginTop: 50,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    paddingTop: 20,
    paddingRight: 0,
    paddingBottom: 20,
    paddingLeft: 0,
  },
  advantageImgBox: {
    width: 120,
    height: 100,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
    color: '#3A3A3A',
    fontSize: 18,
  },
  brandListName: {marginTop: 8, color: '#202020'},
  tabText: {lineHeight: 24},
  tagBox: {
    marginTop: 14,
    marginLeft: 14,
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 10,
    backgroundColor: '#F5F5F6',
    borderRadius: 16,
  },
  tagText: {lineHeight: 32, fontSize: 14, textAlign: 'center', color: '#202020'},
  selected: {backgroundColor: '#E73A32', color: '#f8f8f8'},
  editBtn: {
    position: 'absolute',
    paddingTop: 0,
    paddingRight: 20,
    paddingBottom: 0,
    paddingLeft: 20,
    bottom: 20,
    backgroundColor: '#ff9100',
    borderRadius: 16,
  },
  categoryListName: {marginTop: 8, color: '#202020'},
  starBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#fff',
    borderRadius: 10,
    width: 34,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedText: {color: '#FFFFFF'},
  hotTitle: {marginTop: 16, textAlign: 'center', color: '#3A3A3A', fontSize: 18, fontWeight: '600'},
}
