module.exports = {
  tip: {marginTop: 10, marginRight: 14, marginBottom: 10, marginLeft: 14, color: '#999'},
  pageBox: {height: '100%', backgroundColor: '#f8f8f8'},
  btn3: {textAlign: 'center', zIndex: 9999, position: 'absolute', bottom: 30, width: '100%'},
  btn2Content: {
    paddingTop: 14,
    paddingBottom: 14,
    fontWeight: '800',
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
  },
  friend: {
    backgroundColor: '#fff',
    height: 80,
    marginTop: 0,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    borderRadius: 14,
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    boxSizing: 'border-box',
  },
  btn: {color: '#3A3A3A', flexDirection: 'row', alignItems: 'center'},
  leftWrap: {flexDirection: 'row'},
  avatar: {width: 50, height: 50, marginRight: 14},
  vipLogo: {width: 14},
  name: {color: '#3A3A3A'},
  footer: {paddingTop: 14, fontSize: 14, color: '#7C7C7C'},
}
