module.exports = {
  page: {backgroundColor: '#f7f7f7', height: '100%'},
  wrapItem: {
    marginTop: 20,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    paddingTop: 20,
    paddingRight: 14,
    paddingBottom: 20,
    paddingLeft: 14,
    borderRadius: 10,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  input: {paddingTop: 0, paddingRight: 20, paddingBottom: 0, paddingLeft: 20},
  line: {
    backgroundColor: '#fa534f',
    height: 40,
    width: 6,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    borderBottomLeftRadius: 0,
    position: 'absolute',
    left: -14,
    top: -10,
  },
  label: {fontSize: 16, paddingLeft: 10},
  value: {fontSize: 16, color: 'black'},
  productBox: {paddingTop: 0, paddingRight: 20, paddingBottom: 0, paddingLeft: 20},
  invoiceBox: {paddingTop: 0, paddingRight: 20, paddingBottom: 0, paddingLeft: 20},
  productItem: {
    marginBottom: 20,
    borderRadius: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.89)',
    paddingTop: 16,
    paddingRight: 16,
    paddingBottom: 16,
    paddingLeft: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
  },
  avatar: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row', alignItems: 'center'},
  status: {
    flexDirection: 'row',
    alignItems: 'center',
    fontSize: 14,
    fontWeight: '400',
    color: '#666666',
    lineHeight: 20,
  },
  content: {marginTop: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  productInfo: {flexDirection: 'row', alignItems: 'center'},
  image: {width: 80, height: 80, flexShrink: 0, borderRadius: 7},
  desc: {width: '70%', marginLeft: 10},
  name: {fontSize: 14, fontWeight: '400', color: '#3A3A3A', lineHeight: 20},
  sku: {marginTop: 4, fontSize: 12, fontWeight: '400', color: '#BABABA', lineHeight: 17},
  price: {fontSize: 16, fontWeight: '400', color: '#3A3A3A', marginTop: 4, lineHeight: 20},
  count: {fontSize: 12, fontWeight: '400', color: '#BABABA', lineHeight: 17},
  footer: {marginTop: 26, flexDirection: 'row', justifyContent: 'flex-end'},
  btn: {
    width: 70,
    borderRadius: 15,
    textAlign: 'center',
    marginTop: 0,
    marginRight: 7,
    marginBottom: 0,
    marginLeft: 7,
    fontSize: 13,
    overflow: 'hidden',
  },
  view: {
    borderWidth: 1,
    borderColor: '#9E9E9E',
    borderStyle: 'solid',
    lineHeight: 30,
    borderRadius: 17,
    color: '#9E9E9E',
    marginLeft: 'auto',
  },
  buy: {textAlign: 'center', borderRadius: 17, lineHeight: 30, color: '#fff'},
  invoiceItem: {
    marginTop: 14,
    marginRight: 14,
    marginBottom: 14,
    marginLeft: 14,
    borderRadius: 8,
    backgroundColor: '#fff',
    paddingTop: 16,
    paddingRight: 16,
    paddingBottom: 16,
    paddingLeft: 16,
  },
  content1: {marginTop: 10},
  item: {flexDirection: 'row', alignItems: 'center', height: 40, color: '#898989'},
}
