module.exports = {
  item: {
    borderRadius: 5,
    marginTop: 10,
    marginRight: 20,
    marginBottom: 10,
    marginLeft: 20,
    paddingTop: 7,
    paddingRight: 0,
    paddingBottom: 7,
    paddingLeft: 0,
    backgroundColor: '#fff',
  },
  pageBox: {height: '100%', backgroundColor: '#f8f8f8'},
  infoWrap: {flexDirection: 'column', alignItems: 'center'},
  stepList: {paddingTop: 0, paddingRight: 14, paddingBottom: 0, paddingLeft: 14},
  myStep: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 0,
    marginRight: 40,
    marginBottom: 0,
    marginLeft: 40,
  },
  stepLabel: {marginTop: 10, textAlign: 'center', color: '#1a1a1a'},
  line: {width: '33%', height: 2, top: 7},
  btn: {
    textAlign: 'center',
    backgroundColor: '#E73A32',
    color: '#fff',
    fontSize: 15,
    fontWeight: '400',
    lineHeight: 44,
    borderRadius: 22,
    overflow: 'hidden',
  },
  stepNumBox: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginTop: 0,
    marginRight: 'auto',
    marginBottom: 0,
    marginLeft: 'auto',
  },
  step: {width: '33.3%'},
  image: {width: 50, height: 50, borderRadius: 25, marginTop: 20, marginRight: 0, marginBottom: 12, marginLeft: 0},
  name: {fontSize: 16, fontWeight: '500', color: '#3A3A3A', lineHeight: 24, marginBottom: 35},
  customTitle: {paddingTop: 10, paddingRight: 0, paddingBottom: 10, paddingLeft: 0},
  headerItem: {
    position: 'relative',
    borderRadius: 5,
    marginTop: 80,
    marginRight: 20,
    marginBottom: 10,
    marginLeft: 20,
    height: 150,
    paddingTop: 7,
    paddingRight: 0,
    paddingBottom: 7,
    paddingLeft: 0,
    backgroundColor: '#fff',
  },
  headerAvatar: {position: 'absolute', top: -45},
  headerImage: {width: 90, height: 90, borderRadius: 45, marginRight: 10},
  headerList: {justifyContent: 'center', alignItems: 'center'},
  stepItem: {
    borderTopColor: '#eee',
    borderTopWidth: 1,
    paddingTop: 16,
    paddingRight: 0,
    paddingBottom: 16,
    paddingLeft: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  customValue: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  passLabel: {color: '#3A3A3A', lineHeight: 19, fontSize: 16, fontWeight: 'bold'},
  edit: {
    fontSize: 12,
    color: '#E73A32',
    borderWidth: 1,
    borderColor: '#E73A32',
    borderStyle: 'solid',
    borderRadius: 10,
    paddingTop: 2,
    paddingRight: 4,
    paddingBottom: 2,
    paddingLeft: 4,
  },
  loading: {
    color: '#9E9E9E',
    paddingTop: 15,
    paddingRight: 0,
    paddingBottom: 15,
    paddingLeft: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  icon: {width: 22, marginRight: 10},
  itemBox: {
    borderRadius: 5,
    marginTop: 10,
    marginRight: 20,
    marginBottom: 10,
    marginLeft: 20,
    paddingTop: 15,
    paddingRight: 27,
    paddingBottom: 15,
    paddingLeft: 27,
    backgroundColor: '#fff',
  },
  red: {color: 'red'},
}
