module.exports = {
  page: {backgroundColor: '#f7f7f7', height: '100%', flexGrow: 1, flexShrink: 1, flexBasis: 0},
  btns: {position: 'absolute', bottom: 0, height: 55, width: '100%', flexDirection: 'row', backgroundColor: 'red'},
  clock: {paddingLeft: 10, paddingTop: 15, paddingRight: 12},
  btn1: {textAlign: 'center', fontSize: 18, width: '50%', backgroundColor: '#fff', paddingTop: 18},
  btn3: {textAlign: 'center', fontSize: 18, width: '100%', backgroundColor: '#fff', paddingTop: 18},
  btn2Content: {color: '#ffffff', fontSize: 18, textAlign: 'center', fontWeight: '700'},
  btn2: {textAlign: 'center', fontSize: 18, width: '50%', backgroundColor: '#fff', paddingTop: 18},
  status: {color: '#fff', fontWeight: '800', fontSize: 16},
  time: {marginTop: 2, color: '#fff', fontSize: 14},
  orderStatus: {paddingBottom: 12},
  topContent: {paddingTop: 10},
  image: {borderRadius: 5, marginLeft: 10},
  top: {
    marginTop: 20,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    paddingTop: 20,
    paddingRight: 10,
    paddingBottom: 25,
    paddingLeft: 10,
    backgroundColor: '#fff',
    borderRadius: 15,
    flexDirection: 'row',
  },
  content: {paddingRight: 10, paddingLeft: 10, width: '75%'},
  title: {fontSize: 14, lineHeight: 18},
  spec: {fontSize: 12, marginTop: 2, color: '#9E9E9E'},
  itemIcon: {position: 'absolute', top: 10, right: 0},
  pickItem: {
    paddingTop: 10,
    paddingRight: 16,
    paddingBottom: 10,
    paddingLeft: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickItemBox: {flexDirection: 'row', alignItems: 'center'},
  pickTitle: {color: '#222', fontSize: 14},
  pickLabel: {marginLeft: 20, color: '#969799', fontSize: 14},
  list: {
    marginTop: 20,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    paddingTop: 15,
    paddingRight: 0,
    paddingBottom: 15,
    paddingLeft: 0,
    borderRadius: 15,
    backgroundColor: '#fff',
  },
  itemRightSmall: {paddingTop: 8, paddingBottom: 4},
  input: {width: '100%', borderBottomWidth: 1, borderBottomColor: '#eee', flexDirection: 'row', paddingBottom: 10},
  input2: {width: '100%', flexDirection: 'row', paddingBottom: 0},
  moneyInput: {bottom: 0, height: 30, width: '80%', fontSize: 16},
  inputInfo: {paddingTop: 14, fontSize: 12, color: '#9E9E9E', paddingLeft: 17},
  upload: {width: '100%', height: 200, borderWidth: 1, borderColor: 'black', borderStyle: 'solid'},
  pick: {fontSize: 16},
  addressItem: {flexDirection: 'row', justifyContent: 'space-between'},
  addressInfo: {fontSize: 14, paddingRight: '10%', paddingTop: 30},
  addressInput: {height: 100, paddingRight: 20, fontSize: 14, paddingBottom: 20, right: 0, borderBottomWidth: 0},
  greyContent: {color: '#9E9E9E'},
}
