module.exports = {
  page: {height: '100%', backgroundColor: '#f7f7f7'},
  card: {
    marginTop: 14,
    marginRight: 14,
    marginBottom: 14,
    marginLeft: 14,
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingBottom: 10,
  },
  avatar: {marginTop: 10, width: 50, height: 50, borderRadius: 25},
  cardTop: {flexDirection: 'row', paddingTop: 10, paddingRight: 10, paddingBottom: 10, paddingLeft: 10},
  edit: {paddingTop: 14, paddingRight: 14, paddingBottom: 0, paddingLeft: 14, textAlign: 'right', color: '#3A3A3A'},
  qrcode: {width: 60, height: 60},
  list: {
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  listItem: {flexDirection: 'row', alignItems: 'center', marginBottom: 10},
  icon: {marginRight: 10, width: 20, height: 20},
  menu: {
    marginTop: 14,
    marginRight: 14,
    marginBottom: 14,
    marginLeft: 14,
    borderRadius: 10,
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  menuItem: {alignItems: 'center'},
  menuText: {color: '#3A3A3A'},
  menuIcon: {width: 30, height: 30, marginBottom: 10},
}
