module.exports = {
  chatInput: {paddingTop: 10, backgroundColor: '#ffffff', position: 'absolute', left: 0},
  tool: {
    backgroundColor: '#f7f7f7',
    flexDirection: 'row',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 50,
    paddingLeft: 10,
  },
  toolItem: {marginRight: 20},
  toolImage: {width: 50, height: 50},
  toolText: {marginTop: 6, color: '#9E9E9E', textAlign: 'center', fontSize: 12},
  input: {flexDirection: 'row', alignItems: 'center', paddingBottom: 30, borderBottom: '1px solid #eee'},
  voice: {flexShrink: 0, marginLeft: 10, marginRight: 10, width: 24, height: 24, marginTop: 4},
  add: {width: 24, height: 24, marginTop: 4, marginLeft: 10, marginRight: 10},
  textInput: {
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#eee',
    backgroundColor: '#f7f7f7',
  },
  voiceInput: {
    width: '100%',
    height: 30,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
    borderRadius: 4,
    lineHeight: 30,
    textAlign: 'center',
  },
  btn: {
    overflow: 'hidden',
    height: 40,
    marginTop: 0,
    marginRight: 4,
    marginBottom: 0,
    marginLeft: 4,
    width: 60,
    backgroundColor: '#FF7E80',
    color: '#fff',
    borderRadius: 4,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 40,
  },
  storeButton: {
    backgroundColor: '#f55622',
    height: 20,
    color: '#fff',
    textAlign: 'center',
    fontSize: 12,
    borderRadius: 10,
    lineHeight: 20,
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    marginRight: 20,
    overflow: 'hidden',
  },
}
