module.exports = {
  pageBox: {height: '100%', paddingBottom: 50, backgroundColor: '#f8f8f8'},
  image: {width: 90, height: 90},
  skuRowItem: {flexDirection: 'row'},
  content: {paddingTop: 16, paddingRight: 100, marginLeft: 10},
  spec: {color: '#9E9E9E', paddingTop: 4},
  title: {fontSize: 16},
  cellTitle: {fontSize: 15, color: '#222', paddingLeft: 14, marginBottom: 8},
  skuItem: {
    marginTop: 20,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    borderRadius: 15,
    backgroundColor: '#fff',
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
  },
  starWrap: {backgroundColor: '#fff', paddingTop: 20, paddingRight: 0, paddingBottom: 20, paddingLeft: 0},
  stars: {paddingTop: 10, paddingLeft: 12, height: 30},
  areaWrap: {paddingTop: 6, paddingRight: 6, paddingBottom: 6, paddingLeft: 6},
  modifyBtnWrap: {
    marginTop: 10,
    marginRight: 10,
    marginBottom: 10,
    marginLeft: 10,
    height: 45,
    backgroundColor: '#ff5833',
    borderRadius: 4,
  },
  modifyBtnContent: {
    marginTop: 'auto',
    marginRight: 'auto',
    marginBottom: 'auto',
    marginLeft: 'auto',
    fontSize: 20,
    color: 'white',
    fontWeight: '900',
  },
  btnGroup: {bottom: 0},
  upload: {minHeight: 160},
  skuItemTitle: {color: '#3A3A3A', paddingTop: 14, paddingRight: 0, paddingBottom: 14, paddingLeft: 0},
  anonymous: {paddingTop: 10, paddingBottom: 10},
  anonymousCont: {fontSize: 18, paddingLeft: 10, paddingTop: 3},
}
