module.exports = {
  commentBox: {
    backgroundColor: '#ffffff',
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  commentInfo: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  commentLeft: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row', alignItems: 'center'},
  time: {color: '#9E9E9E'},
  spec: {marginTop: 10, color: '#9E9E9E'},
  commentAvatar: {height: 40, width: 40, borderWidth: 1, borderColor: '#eee', borderRadius: 40, marginRight: 14},
  commentNickname: {marginRight: 14},
  commentContent: {paddingTop: 14, paddingRight: 0, paddingBottom: 14, paddingLeft: 0, fontSize: 16},
  images: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row'},
  labelWrap: {
    flexDirection: 'row',
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    flexWrap: 'wrap',
    minHeight: 50,
  },
  labels: {
    marginRight: 10,
    color: '#9E9E9E',
    backgroundColor: '#f6f6f6',
    paddingTop: 2,
    paddingRight: 4,
    paddingBottom: 2,
    paddingLeft: 4,
    borderRadius: 5,
  },
  labelsActive: {
    marginRight: 10,
    color: '#9E9E9E',
    backgroundColor: '#ff4c2b',
    paddingTop: 2,
    paddingRight: 4,
    paddingBottom: 2,
    paddingLeft: 4,
    borderRadius: 5,
  },
  textUnactive: {color: '#707070'},
  textActive: {color: 'white'},
}
