module.exports = {
  list: {
    marginTop: 20,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    borderRadius: 15,
    backgroundColor: '#fff',
    paddingTop: 12,
    paddingRight: 0,
    paddingBottom: 12,
    paddingLeft: 0,
    borderBottomWidth: 0,
    borderTopWidth: 0,
  },
  item: {backgroundColor: 'transparent', borderBottomWidth: 0, borderTopWidth: 0},
  configTitle: {marginTop: 0, marginRight: 20, marginBottom: 0, marginLeft: 20},
  configText: {color: '#969799'},
  configBox: {
    paddingTop: 12,
    paddingRight: 0,
    paddingBottom: 12,
    paddingLeft: 0,
    backgroundColor: '#fff',
    marginTop: 0,
    marginRight: 15,
    marginBottom: 0,
    marginLeft: 15,
  },
  configItem: {
    paddingTop: 18,
    paddingRight: 16,
    paddingBottom: 18,
    paddingLeft: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  itemTitle: {fontSize: 16},
  leftItem: {flexDirection: 'row', alignItems: 'center'},
  rightItem: {flexDirection: 'row', alignItems: 'center'},
  rightText: {fontSize: 14, color: '#9E9E9E'},
  avatarBox: {
    paddingTop: 11,
    paddingRight: 17,
    paddingBottom: 49,
    paddingLeft: 23,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  nickName: {fontSize: 18, fontWeight: '500', color: '#3A3A3A', lineHeight: 30},
  level: {fontSize: 14, fontWeight: '400', color: '#9E9E9E', lineHeight: 22},
  listWrap: {paddingTop: 10, paddingRight: 0, paddingBottom: 0, paddingLeft: 0, backgroundColor: '#fff'},
  contentTitle: {
    paddingTop: 30,
    paddingRight: 14,
    paddingBottom: 10,
    paddingLeft: 14,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  contentTitleLine: {height: 17, width: 4, borderRadius: 2, backgroundColor: '#FF2050', marginRight: 10},
  contentTitleText: {fontSize: 14, fontWeight: '500', color: '#9E9E9E', lineHeight: 24},
}
