module.exports = {
  skuItem: {marginTop: 20, paddingTop: 8, paddingRight: 8, paddingBottom: 8, paddingLeft: 8},
  content: {
    width: '50%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
  },
  productName: {color: '#333', fontWeight: '400', fontSize: 14},
  spec: {color: '#888', textAlign: 'left', fontSize: 12, paddingTop: 4},
  textInfo: {fontSize: 13, fontWeight: '400', color: '#999999', lineHeight: 25},
  danger: {marginTop: 8, color: '#E73A32', fontSize: 14},
  priceWrap: {marginLeft: 10, flexDirection: 'column', alignItems: 'flex-end'},
  count: {color: '#555555', fontSize: 12, marginTop: 10},
  remind: {marginLeft: 14, fontSize: 14, fontWeight: '400', color: '#3A3A3A', lineHeight: 19},
  shopOrderDetail: {height: '100%', backgroundColor: '#EDEDED'},
  skuRowItem: {flexDirection: 'row'},
  itemWrap: {
    marginTop: 20,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    backgroundColor: '#fff',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    borderRadius: 15,
  },
  status: {
    fontSize: 16,
    fontWeight: '500',
    color: '#3A3A3A',
    lineHeight: 17,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {width: 84, height: 84, borderRadius: 10},
  icon: {color: '#000', marginRight: 5, fontSize: 18, lineHeight: 24},
  qrCode: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 'auto',
    marginRight: 'auto',
    marginBottom: 'auto',
    marginLeft: 'auto',
    borderRadius: 10,
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 20,
    paddingLeft: 20,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderStyle: 'solid',
  },
  bottom: {
    borderTopColor: '#EDEDED',
    borderTopWidth: 6,
    paddingTop: 15,
    paddingRight: 0,
    paddingBottom: 15,
    paddingLeft: 0,
    position: 'relative',
  },
  dotLeft: {
    position: 'absolute',
    left: -25,
    top: -18,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#EDEDED',
  },
  dotRight: {
    position: 'absolute',
    right: -25,
    top: -18,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#EDEDED',
  },
  item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 7,
    marginRight: 0,
    marginBottom: 7,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 15,
    paddingBottom: 0,
    paddingLeft: 15,
  },
  label: {fontSize: 14, fontWeight: '600', color: '#666666', lineHeight: 19},
  value: {maxWidth: '80%', flexDirection: 'row', alignItems: 'center'},
  text1: {fontSize: 16, fontWeight: '600', color: '#666666'},
  btnWrap: {
    lineHeight: 40,
    borderRadius: 20,
    textAlign: 'center',
    backgroundColor: '#333',
    color: '#fff',
    marginTop: 20,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    overflow: 'hidden',
  },
  top: {textAlign: 'center', paddingTop: 50, paddingRight: 0, paddingBottom: 33, paddingLeft: 0},
  price: {flexDirection: 'row', alignItems: 'center', justifyContent: 'center'},
  type: {textAlign: 'center', marginTop: 20, fontSize: 20, fontWeight: '600', color: '#999999'},
  conditions: {justifyContent: 'center', alignItems: 'flex-end', flexDirection: 'row', marginTop: 33},
  label2: {fontSize: 15, fontWeight: 'bold', color: '#999999'},
  label1: {backgroundColor: 'transparent', fontSize: 15, fontWeight: 'bold', color: '#999999'},
  time: {marginTop: 31, flexDirection: 'row', alignItems: 'center', justifyContent: 'center'},
  productCountDown: {flexDirection: 'row'},
  item2: {fontSize: 15, color: '#666666'},
  item1: {fontSize: 15, color: '#FB622C'},
  'appointment-detail': {width: '100%', height: '100vh', overflow: 'auto', backgroundColor: '#EDEDED'},
  __viewportUnits: true,
  note: {marginTop: 20, marginRight: 20, marginBottom: 20, marginLeft: 20},
  title: {fontSize: 15, fontWeight: '400', color: '#999999', lineHeight: 25},
  groupWrap: {marginTop: 0, marginRight: 20, marginBottom: 0, marginLeft: 20},
  openBtn: {width: '100%', paddingTop: 10, paddingRight: 0, paddingBottom: 10, paddingLeft: 0, borderRadius: 40},
  btnBox: {flexDirection: 'row', marginTop: 10, justifyContent: 'flex-end'},
  btnItem: {
    color: '#3A3A3A',
    borderWidth: 1,
    borderColor: '#3A3A3A',
    paddingTop: 0,
    paddingRight: 6,
    paddingBottom: 0,
    paddingLeft: 6,
    borderRadius: 15,
    lineHeight: 20,
    fontSize: 10,
  },
}
