module.exports = {
  header: {height: 100, marginTop: 14, marginRight: 14, marginBottom: 14, marginLeft: 14, flexDirection: 'row'},
  image: {position: 'absolute', width: 50, height: 50, right: 20, top: 25},
  right: {width: '25%', backgroundColor: 'white', borderRadius: 10},
  bg: {backgroundColor: '#f6f6f6', minHeight: '100%'},
  dashedLine: {
    marginTop: 'auto',
    marginRight: 'auto',
    marginBottom: 'auto',
    marginLeft: 'auto',
    width: 1,
    borderWidth: 1,
    borderColor: '#e0e3e3',
    borderStyle: 'dashed',
    height: 80,
  },
  title: {fontSize: 14},
  time: {color: '#9E9E9E', fontSize: 12, paddingTop: 4, paddingBottom: 4},
  place: {color: '#9E9E9E', fontSize: 12},
  btnInactive2: {
    minWidth: 70,
    color: 'white',
    fontSize: 14,
    fontWeight: '800',
    height: 28,
    lineHeight: 28,
    textAlign: 'center',
  },
  btnInactiveWrap2: {
    marginTop: 'auto',
    marginRight: 'auto',
    marginBottom: 'auto',
    marginLeft: 'auto',
    borderRadius: 16,
    backgroundColor: '#8e8e8e',
  },
  lineBtn: {color: 'white', fontSize: 14, fontWeight: '800', textAlign: 'center', lineHeight: 28},
  lineBtnWrap: {
    marginTop: 'auto',
    marginRight: 'auto',
    marginBottom: 'auto',
    marginLeft: 'auto',
    borderRadius: 14,
    height: 28,
    minWidth: 70,
  },
  btnWrap: {marginTop: 'auto', marginRight: 'auto', marginBottom: 'auto', marginLeft: 'auto', lineHeight: 28},
  price: {
    minWidth: 80,
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
    height: 80,
    marginRight: 10,
    borderRadius: 10,
    position: 'relative',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  priceWrap: {flexDirection: 'row', alignItems: 'center', justifyContent: 'center'},
  unit: {color: '#fff', fontSize: 14},
  conditions: {width: '100%', textAlign: 'center', fontSize: 11, fontWeight: '400', color: '#fff', lineHeight: 16},
  priceUnit: {color: '#fff', fontSize: 12, fontWeight: 'bold', position: 'relative', bottom: 10},
  priceAmount: {color: '#fff', fontSize: 28},
  left: {
    alignItems: 'center',
    backgroundColor: 'white',
    flexDirection: 'row',
    borderRadius: 10,
    paddingLeft: 10,
    width: '75%',
  },
  dot: {backgroundColor: '#fff', position: 'absolute', width: 8, height: 8, borderRadius: 4, left: -4},
}
