module.exports = {
  bg: {backgroundColor: '#fff'},
  header: {
    marginTop: 7,
    marginRight: 14,
    marginBottom: 7,
    marginLeft: 14,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 10,
  },
  nameBox: {
    marginTop: 0,
    marginRight: 40,
    marginBottom: 0,
    marginLeft: 40,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
  },
  downloadText: {marginTop: 20, marginRight: 50, marginBottom: 20, marginLeft: 50, textAlign: 'center'},
  downloadName: {color: '#000', textAlign: 'center'},
  likeBtn: {
    marginRight: 10,
    paddingTop: 6,
    paddingRight: 8,
    paddingBottom: 6,
    paddingLeft: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#b1b1b1',
    borderStyle: 'solid',
    width: 80,
    marginBottom: 10,
  },
  btnBox: {
    backgroundColor: '#ff6f2e',
    textAlign: 'center',
    marginTop: 20,
    marginRight: 'auto',
    marginBottom: 20,
    marginLeft: 'auto',
    paddingTop: 10,
    paddingRight: 20,
    paddingBottom: 10,
    paddingLeft: 20,
    borderRadius: 2,
  },
  btnText: {color: '#FFFFFF', textAlign: 'center'},
  downloadImg: {width: '100%'},
  like: {color: '#b1b1b1', textAlign: 'center', fontSize: 12},
  icon: {
    paddingTop: 3,
    paddingRight: 6,
    paddingBottom: 3,
    paddingLeft: 6,
    position: 'absolute',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 0,
  },
  iconText: {fontSize: 14, fontWeight: '400', color: '#FFFFFF', lineHeight: 18},
  leftTitle: {color: '#333'},
  image: {width: 80, borderRadius: 4, height: 80},
  right: {paddingLeft: 10},
  eachItem: {paddingTop: 15, paddingBottom: 10, width: '100%'},
  productSpec: {
    width: '80%',
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: '#9E9E9E',
    fontSize: 13,
  },
  priceInfo: {
    width: '100%',
    paddingBottom: 20,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  createdTime: {color: '#9E9E9E', fontSize: 13},
  totalInfo: {fontSize: 14, color: '#222222', fontWeight: '500'},
  totalInfo1: {color: '#222', fontSize: 13},
  eachPrice: {textAlign: 'right', marginLeft: 10, color: '#9E9E9E'},
  eachTitle: {width: '80%', fontSize: 14, color: '#222222'},
  statusContext: {color: '#3A3A3A', fontSize: 16, textAlign: 'right'},
  statusLabel: {position: 'absolute', top: 4, right: 0},
  name: {flexDirection: 'row', alignItems: 'center'},
  nameText: {color: '#222222', fontSize: 16, fontWeight: 'bold'},
  headerWrapper: {width: '100%', paddingTop: 4, position: 'relative', paddingBottom: 10},
  buyAgain: {textAlign: 'center', fontSize: 12, color: 'white'},
  buyAgainBtn: {
    width: 80,
    marginBottom: 4,
    marginRight: 8,
    paddingTop: 6,
    paddingRight: 8,
    paddingBottom: 6,
    paddingLeft: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#ff585e',
    borderStyle: 'solid',
    backgroundColor: '#ff585e',
  },
  footer: {textAlign: 'right', paddingTop: 20, width: '100%', paddingBottom: 10},
  payInfo: {paddingBottom: 20, flexDirection: 'column', alignItems: 'flex-end'},
  overlay: {position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, zIndex: 100},
  showMenuTitle: {
    top: 0,
    zIndex: 101,
    color: '#3A3A3A',
    position: 'absolute',
    backgroundColor: '#fff',
    lineHeight: 40,
    height: 40,
    fontSize: 16,
    fontWeight: 'bold',
    paddingLeft: 14,
  },
  itemBox: {flexDirection: 'row', flexWrap: 'wrap', paddingBottom: 20},
  userAvatar: {width: 30, height: 30, borderRadius: 15, marginRight: 10},
  itemWrap: {
    width: '19%',
    marginTop: 5,
    marginRight: '3%',
    marginBottom: 5,
    marginLeft: '3%',
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#eee',
  },
  itemWrapActive: {borderColor: '#90A96E', backgroundColor: 'rgba(144, 169, 110, 0.1)'},
  itemTitle: {fontSize: 12, lineHeight: 30, color: '#999'},
}
