module.exports = {
  li: {
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    flexDirection: 'row',
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  left: {flexDirection: 'row', width: '70%'},
  nickname: {fontSize: 16},
  image: {width: 50, height: 50, borderRadius: 25},
  content: {marginLeft: 10},
  contentText: {marginTop: 8, fontSize: 16, color: '#9E9E9E'},
  right: {wordBreak: 'break-all', width: '30%'},
  distance: {fontSize: 14, color: '#9E9E9E', textAlign: 'right'},
  serviceName: {color: '#E73A32'},
  count: {
    marginTop: 4,
    backgroundColor: '#F05D5D',
    borderRadius: 8,
    overflow: 'hidden',
    minWidth: 16,
    textAlign: 'center',
    height: 16,
    lineHeight: 16,
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  navWrap: {marginTop: 20, flexDirection: 'row', justifyContent: 'space-around'},
  hisIcon: {width: 52, height: 52, borderRadius: 26},
  label: {marginTop: 14, fontSize: 13, fontWeight: '500', color: '#2C2C2C', lineHeight: 18, textAlign: 'center'},
}
