module.exports = {
  warningBar: {backgroundColor: '#ffefed', paddingTop: 8, paddingBottom: 8, paddingLeft: 14},
  nickname: {fontSize: 18, color: '#9E9E9E', paddingRight: 40},
  wrap: {flexDirection: 'row'},
  btn3: {marginTop: 30, marginRight: 15, marginBottom: 30, marginLeft: 15, textAlign: 'center', borderRadius: 5},
  btn2Content: {
    paddingTop: 14,
    paddingBottom: 14,
    fontWeight: '800',
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
  },
  icon: {position: 'absolute', right: 0},
  input: {width: '70%'},
  iconText: {color: '#E73A32', paddingLeft: 12},
  infoPanel: {paddingTop: 40, paddingLeft: 20, paddingRight: 30, paddingBottom: 40},
  panelTit: {fontSize: 16, fontWeight: 'bold'},
  panelContent: {color: '#9E9E9E', paddingTop: 20, lineHeight: 25},
}
