module.exports = {
  helpBox: {marginTop: 50},
  helpLabel: {color: '#323233', fontSize: 14, lineHeight: 24},
  helpTittle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#202020',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingRight: 16,
    paddingBottom: 10,
    paddingLeft: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ebedf0',
  },
  helpList: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingRight: 16,
    paddingBottom: 10,
    paddingLeft: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ebedf0',
  },
  minePage: {height: '100%', backgroundColor: '#f7f7f7'},
  touch: {flexGrow: 1, flexShrink: 1, flexBasis: 0},
  top: {
    paddingTop: 0,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  signIn: {
    flexDirection: 'row',
    position: 'absolute',
    right: 0,
    display: 'flex',
    alignItems: 'center',
    fontWeight: 'bold',
    backgroundColor: '#fff5d9',
    paddingTop: 4,
    paddingRight: 14,
    paddingBottom: 4,
    paddingLeft: 14,
    borderBottomLeftRadius: 20,
    borderTopLeftRadius: 20,
    wordBreak: 'keep-all',
  },
  my: {fontSize: 20, color: '#222222', fontWeight: 'bold'},
  attention: {
    marginLeft: 5,
    paddingTop: 0,
    paddingRight: 12,
    paddingBottom: 0,
    paddingLeft: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    opacity: 0.8,
    height: 24,
  },
  userInfo: {
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 20,
    paddingLeft: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  labelBox: {width: 300, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center'},
  labelView: {
    paddingTop: 0,
    paddingRight: 12,
    paddingBottom: 0,
    paddingLeft: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    opacity: 0.8,
    marginTop: 8,
    marginRight: 8,
    height: 24,
  },
  labelText: {lineHeight: 24, color: '#666666', fontSize: 12},
  headerBox: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  avatar: {flexDirection: 'row', alignItems: 'flex-start'},
  nickname: {fontSize: 18, fontWeight: '500', color: '#3A3A3A'},
  phone: {color: '#222222', marginTop: 4},
  image: {width: 60, height: 60, borderRadius: 30, marginRight: 10},
  menuList: {
    paddingTop: 14,
    paddingRight: 30,
    paddingBottom: 14,
    paddingLeft: 30,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
  },
  menuItem: {textAlign: 'center', width: '25%'},
  mineAvatar: {width: 60, height: 60},
  menuNum: {color: '#fff', fontWeight: 'bold', fontSize: 20, textAlign: 'center'},
  menuTitle: {color: '#fff', textAlign: 'center', fontWeight: 'bold', marginTop: 6},
  bacText: {color: '#fff'},
  bac: {
    height: 70,
    marginTop: 16,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    borderRadius: 8,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 20,
  },
  betweenMenu: {
    flexDirection: 'column',
    paddingTop: 6,
    paddingRight: 14,
    paddingBottom: 30,
    paddingLeft: 14,
    marginTop: 16,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    borderRadius: 8,
    backgroundColor: '#fff',
    fontSize: 16,
  },
  mineInfoBox: {flexDirection: 'row'},
  cardTitle: {color: '#222222', fontSize: 15, fontWeight: '500'},
  bacImage: {borderRadius: 8, width: '100%'},
  support: {marginTop: 36, marginRight: 0, marginBottom: 72, marginLeft: 0, color: '#9E9E9E', opacity: 0.5},
  supportImage: {width: 55, height: 15, marginTop: 0, marginRight: 'auto', marginBottom: 0, marginLeft: 'auto'},
  supportText: {marginTop: 6, fontSize: 10, textAlign: 'center', color: '#9E9E9E'},
  borderBottom: {borderBottomWidth: 1, borderBottomColor: '#eee'},
  cardHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  mineHeaderName: {marginLeft: 5, paddingTop: 2, color: '#000000', fontSize: 16, paddingBottom: 2},
  mineHeaderSpec: {marginLeft: 5, paddingTop: 2, color: '#ababab', fontSize: 12, paddingBottom: 2},
  mineHeader: {
    paddingTop: 14,
    paddingRight: 0,
    paddingBottom: 14,
    paddingLeft: 0,
    color: '#3A3A3A',
    fontSize: 16,
    fontWeight: '500',
  },
  menuPoint: {color: '#9E9E9E', flexDirection: 'row', alignItems: 'center', fontSize: 14},
  mineImageWrap: {textAlign: 'center'},
  mineImage: {width: 22, height: 22, marginTop: 0, marginRight: 'auto', marginBottom: 0, marginLeft: 'auto'},
  unit: {fontSize: 12, color: '#9E9E9E', fontWeight: 'normal'},
  mineListWrap: {
    marginTop: 16,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    borderRadius: 8,
    backgroundColor: '#fff',
    fontSize: 16,
  },
  conditionsLabel: {position: 'absolute', borderRadius: 18, overflow: 'hidden', right: 20, top: 18},
  conditions: {
    paddingTop: 0,
    paddingRight: 12,
    paddingBottom: 0,
    paddingLeft: 12,
    lineHeight: 28,
    fontWeight: '500',
    color: '#3A3A3A',
    fontSize: 14,
  },
  loginBox: {
    borderRadius: 8,
    marginTop: 0,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    backgroundColor: '#FFFFFF',
  },
  mineList: {
    paddingTop: 16,
    paddingRight: 0,
    paddingBottom: 16,
    paddingLeft: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  mineItem: {textAlign: 'center', marginTop: 17, marginRight: 0, marginBottom: 17, marginLeft: 0, width: '25%'},
  mineNum: {color: '#222222', fontSize: 20, textAlign: 'center', maxHeight: 24},
  mineTitle: {color: '#222222', textAlign: 'center', marginTop: 16, fontSize: 14},
  listBox: {
    marginTop: 24,
    marginRight: 24,
    marginBottom: 24,
    marginLeft: 24,
    borderRadius: 20,
    backgroundColor: '#fff',
    paddingTop: 0,
    paddingRight: 18,
    paddingBottom: 0,
    paddingLeft: 18,
  },
  listBoxWrap: {
    paddingTop: 18,
    paddingRight: 0,
    paddingBottom: 18,
    paddingLeft: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  listBoxWrapBorder: {borderBottomWidth: 1, borderBottomColor: '#eee'},
  listText: {flexDirection: 'row', alignItems: 'center'},
  likeTitle: {
    fontWeight: '500',
    paddingTop: 0,
    paddingRight: 20,
    paddingBottom: 0,
    paddingLeft: 20,
    color: '#222222',
    marginTop: 0,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    fontSize: 16,
  },
  listLabel: {fontSize: 15, color: '#222222'},
  listImage: {width: 24, height: 24, marginRight: 20},
  unread: {
    textAlign: 'center',
    width: 18,
    height: 18,
    position: 'absolute',
    top: -10,
    right: -10,
    fontSize: 10,
    borderRadius: 9,
    backgroundColor: '#FF4A4A',
  },
  mineDot: {
    textAlign: 'center',
    width: 20,
    height: 20,
    position: 'absolute',
    top: -10,
    right: 10,
    fontSize: 14,
    borderRadius: 10,
    backgroundColor: '#FF4A4A',
  },
  mineIcon: {marginLeft: 30},
  loginBtn: {fontSize: 16, fontWeight: 'bold', color: '#222222', marginTop: 20, marginLeft: 14},
  infoItem: {width: '25%'},
  menuIconBox: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center'},
  total: {textAlign: 'center', color: '#3A3A3A', fontSize: 18, height: 22},
  propName: {textAlign: 'center', marginTop: 12, fontSize: 14, color: '#9E9E9E'},
  btnBox: {flexDirection: 'column', alignItems: 'center'},
  popupItemBorder: {width: '100%', borderTopColor: '#eee', borderTopWidth: 1},
  popupItem: {
    paddingTop: 20,
    paddingRight: 0,
    paddingBottom: 20,
    paddingLeft: 0,
    textAlign: 'center',
    color: '#3A3A3A',
    fontSize: 16,
  },
  bottomMenu: {marginTop: 10, flexDirection: 'row', alignItems: 'center'},
  promoteText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '400',
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    lineHeight: 20,
  },
  bottomMenuItem: {
    fontSize: 11,
    fontWeight: '400',
    color: '#5d5d5d',
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
  },
  logisticsBox: {backgroundColor: '#F8F8F8', borderRadius: 10, position: 'relative', marginBottom: 14},
  logisticsIcon: {width: 80, height: 80, borderRadius: 6, marginRight: 10},
  logisticsInfo: {
    paddingTop: 6,
    paddingRight: 6,
    paddingBottom: 6,
    paddingLeft: 6,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  logisticsCompany: {
    fontSize: 10,
    borderRadius: 8,
    lineHeight: 16,
    paddingTop: 0,
    paddingRight: 5,
    paddingBottom: 0,
    paddingLeft: 5,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderStyle: 'solid',
    color: '#999999',
    marginLeft: 10,
  },
  logisticsDesc: {width: '70%'},
  status: {color: '#222222', flexDirection: 'row', alignItems: 'center'},
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 0,
    paddingRight: 14,
    paddingBottom: 0,
    paddingLeft: 14,
  },
  address: {marginTop: 10, color: '#888', fontSize: 12},
  homeSpace: {position: 'absolute', right: 20, top: 0, flexDirection: 'row', alignItems: 'center'},
  homeSpaceText: {fontSize: 14, color: '#3A3A3A', lineHeight: 18},
  mineNav: {
    paddingBottom: 20,
    marginTop: 0,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  identity: {fontSize: 14, color: '#3A3A3A', paddingLeft: 14},
  mineNavTitle: {textAlign: 'center', fontSize: 18, fontWeight: '500', color: '#3A3A3A', lineHeight: 22},
  config: {flexDirection: 'row', fontSize: 14},
  configImage: {width: 22, height: 22, marginRight: 5},
  mainMenuChoose: {
    paddingTop: 15,
    paddingRight: 15,
    paddingBottom: 15,
    paddingLeft: 15,
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
  },
  popupTitle: {textAlign: 'center', fontSize: 15, fontWeight: '400', color: '#000000'},
  modalMenuList: {
    paddingTop: 35,
    paddingRight: 10,
    paddingBottom: 60,
    paddingLeft: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  item: {
    paddingTop: 4,
    paddingRight: 10,
    paddingBottom: 4,
    paddingLeft: 10,
    marginBottom: 30,
    borderRadius: 6,
    backgroundColor: '#EEEEEE',
    width: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
  },
  itemText: {textAlign: 'center', fontSize: 12, fontWeight: '500', color: '#ABAAB0'},
  active: {
    paddingTop: 4,
    paddingRight: 10,
    paddingBottom: 4,
    paddingLeft: 10,
    marginTop: 10,
    borderRadius: 6,
    backgroundColor: '#07C160',
    width: 100,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
  },
  activeText: {textAlign: 'center', fontSize: 12, fontWeight: '500', color: '#fff'},
  ruleLink: {color: '#666666', fontSize: 14, lineHeight: 24},
  qrCode: {
    position: 'absolute',
    right: 0,
    bottom: 25,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 16,
    borderTopLeftRadius: 17,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 17,
    borderWidth: 1,
    borderColor: '#eee',
  },
  qrCodeText: {lineHeight: 34, fontSize: 13, fontWeight: '400', color: '#3A3A3A'},
}
