module.exports = {
  image: {width: 60, height: 60, position: 'absolute', right: 40, bottom: 0},
  icon: {width: 30},
  orderInfo: {
    backgroundColor: 'white',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    paddingTop: 30,
    paddingBottom: 30,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingLeft: 10,
    alignItems: 'center',
  },
  orderInfoContent: {paddingBottom: 4},
  desc: {marginTop: 5, color: '#666', fontSize: 14, lineHeight: 16},
  btnWrap: {height: 130, paddingTop: 40, paddingRight: 40, paddingBottom: 40, paddingLeft: 40},
  orderStatus: {
    color: '#3A3A3A',
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topStatus: {color: 'white', paddingTop: 20, fontSize: 20, fontWeight: 'bold', left: 25},
  topContent: {left: 25, color: 'white', paddingTop: 5, fontSize: 14},
  address: {
    backgroundColor: '#fff',
    marginTop: 14,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    paddingTop: 10,
    paddingRight: 0,
    paddingBottom: 10,
    paddingLeft: 0,
    borderRadius: 15,
  },
  addressInfo: {
    backgroundColor: 'white',
    width: '100%',
    height: 75,
    marginTop: 10,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
  },
  content: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row'},
  contentWrap: {width: '80%'},
  addressIcon: {paddingLeft: 10, paddingRight: 10, paddingTop: 30},
  t1: {paddingTop: 20},
  t2: {bottom: 14, fontSize: 14, color: '#ababab'},
  callHelper: {width: '100%', textAlign: 'center', color: '#ababab'},
  helper: {marginBottom: 10},
  rightValue: {textAlign: 'right', width: 160, color: '#9E9E9E'},
  goodsInfo: {paddingTop: 0, paddingRight: 10, paddingBottom: 0, paddingLeft: 10, backgroundColor: '#fff'},
  totalView: {width: '100%', borderWidth: 1, borderColor: 'black', borderStyle: 'solid', height: 10},
  label: {fontSize: 16, fontWeight: '400', paddingBottom: 2, paddingLeft: 2},
  totalRealMoney: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row-reverse'},
  realMoney: {top: -2},
  leftMoney: {color: '#9E9E9E'},
  btnGroup: {
    borderTopWidth: 1,
    paddingTop: 20,
    paddingBottom: 30,
    borderColor: '#eee',
    paddingRight: 20,
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  bg: {backgroundColor: '#fff', height: '100%', flexGrow: 1, flexShrink: 1, flexBasis: 0},
  mainBody: {backgroundColor: '#f6f6f6', paddingBottom: 150},
  btn: {marginRight: 5},
  btn1: {marginRight: 5},
  btn3: {marginRight: 5},
  likeBtn: {
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#333',
    borderStyle: 'solid',
  },
  likeBtn1: {
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
  },
  likeBtn2: {
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    borderWidth: 1,
    borderColor: '#333',
    borderStyle: 'solid',
  },
  likeBtn3: {
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
    borderWidth: 1,
    borderColor: '#FF2A41',
    borderStyle: 'solid',
  },
  like: {textAlign: 'center', fontSize: 12, lineHeight: 30},
  like1: {fontWeight: 'bold', textAlign: 'center', fontSize: 12, lineHeight: 30},
  like2: {textAlign: 'center', fontSize: 12, color: '#333', lineHeight: 30},
  like3: {textAlign: 'center', fontSize: 12, color: '#FF2A41', lineHeight: 30},
  iconLeft: {marginTop: 50, marginLeft: 20},
  headerWrapper: {width: '100%', paddingTop: 4, position: 'relative', paddingBottom: 10},
  name: {flexDirection: 'row', alignItems: 'center'},
  nameText: {fontSize: 16, fontWeight: 'bold'},
}
