module.exports = {
  image: {width: 100, borderRadius: 5, height: 100, backgroundColor: '#f6f6f6'},
  warningBar: {
    backgroundColor: '#ffefed',
    width: '100%',
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 14,
  },
  topCard: {
    paddingTop: 24,
    paddingRight: 16,
    paddingBottom: 24,
    paddingLeft: 16,
    borderRadius: 8,
    marginTop: 7,
    marginRight: 14,
    marginBottom: 7,
    marginLeft: 14,
  },
  trackPage: {position: 'relative', backgroundColor: '#fff', height: '100%'},
  packageList: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingTop: 15,
    paddingRight: 15,
    paddingBottom: 15,
    paddingLeft: 15,
  },
  iconText: {color: '#FA632C', paddingLeft: 14},
  priceWrap: {marginTop: 10, marginRight: 0, marginBottom: 10, marginLeft: 0, fontSize: 14},
  time: {paddingTop: 4, marginTop: 2, fontSize: 12, marginBottom: 8},
  rightTextName: {color: '#3A3A3A', fontSize: 16},
  left: {width: '80%'},
  right: {width: '20%'},
  rightAmount: {textAlign: 'right', fontSize: 16, color: '#FB6D6D', width: 100},
  listItem: {backgroundColor: '#fff'},
  top: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  deleteBtn: {
    paddingTop: 6,
    paddingRight: 10,
    paddingBottom: 6,
    paddingLeft: 10,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
  },
  deleteText: {fontSize: 12, color: '#3A3A3A'},
  likeBtn: {
    paddingTop: 6,
    paddingRight: 10,
    paddingBottom: 6,
    paddingLeft: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#FF2A41',
    borderStyle: 'solid',
  },
  likeText: {fontSize: 12, color: '#FF2A41'},
  footer: {textAlign: 'right', width: '100%'},
}
