module.exports = {
  signInPage: {height: '100%', backgroundColor: '#f7f7f7'},
  header: {height: 100, backgroundColor: '#FF2A41'},
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    marginTop: -50,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
  },
  iconImage: {marginTop: -24, width: 150},
  btnWrap: {paddingTop: 14, paddingRight: 14, paddingBottom: 14, paddingLeft: 14},
  tip: {fontSize: 14, color: '#999999', marginBottom: 10},
  btnBox: {
    borderRadius: 30,
    backgroundColor: '#FF2A41',
    paddingTop: 4,
    paddingRight: 15,
    paddingBottom: 4,
    paddingLeft: 15,
  },
  btn: {
    paddingTop: 4,
    paddingRight: 0,
    paddingBottom: 4,
    paddingLeft: 0,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
  },
  monthBtn: {lineHeight: 30, fontSize: 13, fontWeight: 'bold', textAlign: 'center', color: '#3A3A3A'},
  active: {color: 'white', backgroundColor: '#FF2A41'},
  today: {marginTop: 5, textAlign: 'center', fontSize: 12, fontWeight: '500', color: '#9E9E9E'},
  monthSelect: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center', fontSize: 18},
  dayText: {textAlign: 'center', fontSize: 20, lineHeight: 35, marginTop: -4, color: 'white !important'},
  month: {marginTop: 0, marginRight: 20, marginBottom: 0, marginLeft: 20, fontSize: 18},
  day: {textAlign: 'center', fontSize: 20, lineHeight: 35, color: '#222222', marginTop: -4},
  dayBox: {
    marginTop: 0,
    marginRight: 'auto',
    marginBottom: 0,
    marginLeft: 'auto',
    borderRadius: 15,
    height: 30,
    width: 30,
  },
  signBox: {
    marginTop: 20,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
    borderRadius: 20,
    backgroundColor: '#fff',
    paddingTop: 20,
    paddingRight: '1%',
    paddingBottom: 20,
    paddingLeft: '1%',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  item: {paddingTop: 10, paddingRight: 0, paddingBottom: 10, paddingLeft: 0, width: '14%'},
}
