module.exports = {
  yuFlex: {flexDirection: 'row', alignItems: 'center'},
  iconImage: {marginTop: 10},
  homeWrapBox: {
    borderRadius: 12,
    marginRight: 20,
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    width: 140,
    height: 100,
  },
  playIcon: {width: 30, height: 30, marginTop: 'auto', marginRight: 'auto', marginBottom: 'auto', marginLeft: 'auto'},
  listItem: {
    marginTop: 20,
    flexDirection: 'row',
    fontSize: 0,
    paddingTop: 7,
    paddingRight: 7,
    paddingBottom: 7,
    paddingLeft: 7,
    boxSizing: 'border-box',
    width: '100%',
    borderRadius: 10,
    marginBottom: 14,
  },
  bottom: {position: 'relative', paddingTop: 6, paddingRight: 10, paddingBottom: 6, paddingLeft: 10},
  bottomText: {marginBottom: 6, fontSize: 16, fontWeight: 'bold'},
  avatarRight: {flexDirection: 'row', alignItems: 'center', position: 'absolute', bottom: 20, right: 40, color: '#999'},
}
