module.exports = {
  right: {flexDirection: 'row', alignItems: 'center', height: 60, paddingBottom: 14, paddingRight: 14},
  pageContent: {color: '#222222', paddingTop: 14, paddingRight: 14, paddingBottom: 14, paddingLeft: 14},
  contentInfo: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  left: {flexDirection: 'row', alignItems: 'center'},
  contentTitle: {fontSize: 16, fontWeight: 'bold'},
  spec: {fontSize: 12, color: '#9E9E9E', flexDirection: 'row', alignItems: 'center', marginTop: 5},
  downloadBtn: {marginLeft: 14, flexDirection: 'row', alignItems: 'center'},
  downloadBtnText: {color: '#f82b22', fontSize: 14},
  content: {marginTop: 14, marginRight: 0, marginBottom: 14, marginLeft: 0, minHeight: 30, fontSize: 16, color: '#666'},
  shop: {
    backgroundColor: '#f7f7f7',
    borderRadius: 10,
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    marginBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  spuRight: {width: '95%', marginLeft: 10, paddingRight: 80, paddingBottom: 14, position: 'relative'},
  priceInfo: {position: 'absolute', bottom: 8, flexDirection: 'row', justifyContent: 'space-between', width: '100%'},
  yuFlex: {flexDirection: 'row', alignItems: 'center'},
  originalPrice: {
    marginTop: 4,
    marginLeft: 10,
    textDecorationLine: 'line-through',
    textDecorationColor: '#9E9E9E',
    textDecorationStyle: 'solid',
    color: '#9E9E9E',
    fontSize: 12,
  },
}
