module.exports = {
  chatItem: {width: '100%', flexDirection: 'column', alignItems: 'center', marginBottom: 20},
  chatItemContent: {width: '100%', flexDirection: 'row'},
  contentWrap: {maxWidth: '60%'},
  avatar: {width: 40, height: 40, borderRadius: 20, marginLeft: 10, marginRight: 10},
  chatContent: {marginTop: 2},
  isMyWordStyle: {
    backgroundColor: '#FF7E80',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 6,
    borderBottomRightRadius: 24,
    borderBottomLeftRadius: 24,
    paddingTop: 13,
    paddingRight: 20,
    paddingBottom: 13,
    paddingLeft: 20,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
  },
  isMyWordStyleText: {fontSize: 16, color: '#fff', lineHeight: 20},
  image: {width: 75, height: 140, borderRadius: 10},
  isOtherWordStyle: {
    borderTopLeftRadius: 6,
    borderTopRightRadius: 24,
    borderBottomRightRadius: 24,
    borderBottomLeftRadius: 24,
    paddingTop: 13,
    paddingRight: 20,
    paddingBottom: 13,
    paddingLeft: 20,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
    backgroundColor: '#FFFFFF',
  },
  isOtherWordStyleText: {fontSize: 16, lineHeight: 20, color: '#3A3A3A'},
  isRead: {textAlign: 'right', fontSize: 12, color: '#ababab', marginTop: 5},
  voiceItem: {
    marginTop: 5,
    borderRadius: 10,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    color: '#666666',
    fontSize: 26,
    backgroundColor: '#fff',
    flexDirection: 'row',
  },
  right: {
    justifyContent: 'flex-end',
    textAlign: 'right',
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
    backgroundColor: '#fff',
  },
  time: {marginTop: 20, marginBottom: 20, fontSize: 12, color: '#9E9E9E'},
  voicePlaySize: {width: 11, height: 16},
  voiceDurationStyle: {
    lineHeight: 16,
    paddingTop: 0,
    paddingRight: 6,
    paddingBottom: 0,
    paddingLeft: 6,
    fontSize: 14,
    color: '#9E9E9E',
  },
}
