module.exports = {
  searchBox: {
    width: '100%',
    paddingTop: 0,
    paddingRight: 14,
    paddingBottom: 0,
    paddingLeft: 14,
    marginTop: 10,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 36,
  },
  searchLeft: {width: '85%', flexDirection: 'row', alignItems: 'center'},
  searchRight: {width: '10%', flexDirection: 'column', alignItems: 'center', justifyContent: 'center'},
  searchLabelText: {color: '#3A3A3A', fontSize: 12, marginTop: 5},
  searchIconBox: {height: 30, borderRadius: 15},
  searchText: {lineHeight: 30, color: '#fff'},
  searchWrap: {
    backgroundColor: '#F7F7F7',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  menuIcon: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center'},
  listBox: {flexDirection: 'row'},
  listWrapLeft: {width: '50%', paddingTop: 0, paddingRight: 7, paddingBottom: 0, paddingLeft: 14},
  input: {zIndex: 101, position: 'absolute', top: 0, width: '100%', paddingBottom: 10, backgroundColor: '#fff'},
  overlay: {position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, zIndex: 100},
  listWrapRight: {width: '50%', paddingTop: 0, paddingRight: 14, paddingBottom: 0, paddingLeft: 7},
  listItem: {borderRadius: 8, backgroundColor: '#FFFFFF', overflow: 'hidden'},
  listLabel: {
    paddingTop: 14,
    paddingRight: 6,
    paddingBottom: 14,
    paddingLeft: 6,
    fontSize: 14,
    fontWeight: '400',
    color: '#3A3A3A',
  },
  titleLabel: {lineHeight: 20, height: 40},
  listInfo: {width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 6},
  avatar: {width: 24, height: 24, borderRadius: 12},
  textInput: {width: '100%', fontSize: 14},
  nickname: {fontSize: 13, marginLeft: 6},
  infoLeft: {width: '60%', flexDirection: 'row', alignItems: 'center'},
  infoRight: {flexDirection: 'row', alignItems: 'center'},
  goodIcon: {height: 12, width: 12, marginRight: 4},
  itemBox: {flexDirection: 'row', flexWrap: 'wrap', paddingBottom: 20},
  itemWrap: {
    width: '19%',
    marginTop: 5,
    marginRight: '3%',
    marginBottom: 5,
    marginLeft: '3%',
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#eee',
  },
  itemWrapActive: {borderColor: '#90A96E', backgroundColor: 'rgba(144, 169, 110, 0.1)'},
  itemTitle: {fontSize: 12, lineHeight: 30, color: '#999'},
  itemTitleActive: {color: '#90A96E'},
  showMenuTitle: {
    top: 0,
    color: '#3A3A3A',
    position: 'absolute',
    backgroundColor: '#fff',
    width: '100%',
    lineHeight: 40,
    height: 40,
    fontSize: 16,
    fontWeight: 'bold',
    paddingLeft: 14,
  },
}
