module.exports = {
  input: {
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 10,
    width: '100%',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
  },
  lineLeft: {width: 48, height: 1, marginRight: 8},
  lineRight: {width: 48, height: 1, marginLeft: 8},
  selectLine: {width: 4, height: 21, backgroundColor: '#E73A32', position: 'absolute', top: 10},
  selectTitle: {fontSize: 16, fontWeight: '500', color: '#333'},
  listTitle: {flexDirection: 'row', alignItems: 'center', justifyContent: 'center'},
  mainContainer: {
    borderTopWidth: 1,
    borderTopColor: '#eee',
    marginTop: 50,
    width: '100%',
    height: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  sidebarList: {width: 100, flexShrink: 1},
  sidebarItem: {
    width: 100,
    paddingTop: 10,
    paddingRight: 0,
    paddingBottom: 10,
    paddingLeft: 0,
    backgroundColor: 'red',
    position: 'relative',
  },
  sidebarTitle: {color: '#303133', width: 100, textAlign: 'center'},
  itemImage: {
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 100,
    borderRadius: 6,
    overflow: 'hidden',
  },
  contentItem: {paddingTop: 14, paddingRight: 14, paddingBottom: 14, paddingLeft: 14},
  eachImage: {width: '100%', height: 80},
  itemEachList: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row', flexWrap: 'wrap'},
  eachTitle: {marginTop: 6, fontSize: 14, color: '#303133', textAlign: 'center'},
  itemImageTitle: {
    fontSize: 16,
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 4,
    textShadowColor: '#333',
    color: '#FFFFFF',
  },
  eachBox: {marginTop: 20, marginRight: 0, marginBottom: 20, marginLeft: 0, width: '33%'},
}
