module.exports = {
  freeMallPage: {height: '100%', backgroundColor: '#fff'},
  input: {width: '100%', backgroundColor: '#fff'},
  item: {width: '100%', height: 150, borderRadius: 10, backgroundColor: 'white'},
  image: {width: 120, height: 120, borderRadius: 4},
  inner: {
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderRadius: 10,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  showImg: {marginTop: 20, marginRight: 20, marginBottom: 20, marginLeft: 20},
  eachImage: {borderRadius: 15},
  listBox: {
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    backgroundColor: '#fff',
    color: '#888',
    marginTop: 20,
    marginRight: 20,
    marginBottom: 15,
    marginLeft: 20,
    borderRadius: 10,
  },
  listTitle: {flexDirection: 'row', alignItems: 'center'},
  listText: {
    fontSize: 20,
    paddingTop: 5,
    paddingRight: 0,
    paddingBottom: 5,
    paddingLeft: 0,
    fontWeight: 'bold',
    color: '#222222',
    lineHeight: 38,
  },
  list: {width: '100%', height: 120, overflow: 'hidden', position: 'relative'},
  listWrap: {position: 'absolute'},
  free: {backgroundColor: '#f8f8f8'},
  buy: {backgroundColor: '#f1fcfa'},
  listItem: {
    width: '100%',
    height: 32,
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
    flexDirection: 'row',
    alignItems: 'center',
    fontSize: 11,
    borderRadius: 16,
    color: '#222222',
    marginBottom: 16,
  },
  avatar: {width: 24, height: 24, borderRadius: 12, flexShrink: 0},
  desc: {marginLeft: 10, lineHeight: 20},
  noInfo: {paddingTop: 20, paddingRight: 0, paddingBottom: 20, paddingLeft: 0},
  noInfoText: {textAlign: 'center', fontSize: 12, color: '#222222'},
  selectionItem: {marginTop: 0, marginRight: 10, marginBottom: 0, marginLeft: 10},
  selectionTitle: {color: '#9E9E9E', fontSize: 14},
  selectedTitle: {color: '#222222', fontSize: 16, fontWeight: 'bold', marginTop: -2},
  selectionSubTitle: {color: '#FA632C', fontSize: 12},
  searchWrap: {
    backgroundColor: '#F7F7F7',
    borderRadius: 2,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    marginRight: 22,
    marginBottom: 12,
    marginLeft: 22,
    paddingTop: 8,
    paddingRight: 4,
    paddingBottom: 8,
    paddingLeft: 4,
  },
  menuBox: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    paddingTop: 12,
    paddingRight: 0,
    paddingBottom: 16,
    paddingLeft: 0,
    marginBottom: 10,
  },
  menuImage: {width: 50, height: 50},
  menuLabel: {textAlign: 'center', fontSize: 10, fontWeight: '400', color: '#333333', lineHeight: 14},
  modalBox: {
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    width: '100%',
    backgroundColor: '#fff',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  tabItem: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '20%',
    marginTop: 15,
    marginRight: 6,
    marginBottom: 0,
    marginLeft: 6,
    borderRadius: 8,
    fontSize: 12,
    borderWidth: 1,
    borderColor: '#eee',
    backgroundColor: '#eee',
  },
  activeBox: {borderWidth: 1, borderColor: '#FF2A41', backgroundColor: '#fff'},
  activeText: {color: '#FF2A41'},
  tabText: {lineHeight: 24},
  menuItem1: {textAlign: 'center', width: '25%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center'},
  normal: {color: '#9E9E9E'},
  active: {textAlign: 'center', fontSize: 14, fontWeight: '400', lineHeight: 20, color: '#3A3A3A'},
  menuIcon: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center'},
}
