module.exports = {
  tagImage: {width: 26, height: 26},
  homeColor2: {color: 'yellow'},
  primaryColor: {color: '#E73A32'},
  backgroundColor: {backgroundColor: 'red'},
  pageDefault: {backgroundColor: '#f7f7f7', width: '100%', height: '100%'},
  infoColor: {color: '#909399'},
  textColor: {color: '#3A3A3A'},
  inactive: {color: '#ababab'},
  active: {color: '#E73A32'},
  modalTitle: {textAlign: 'center', fontSize: 18, fontWeight: '500'},
  modalBtnWrap: {marginTop: 20, flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#eee'},
  btpButton: {borderRadius: 30},
  loginTitle: {
    fontSize: 30,
    color: '#303133',
    textAlign: 'center',
    marginTop: 50,
    marginRight: 0,
    marginBottom: 20,
    marginLeft: 0,
  },
  menuNav: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    paddingTop: 0,
    paddingRight: 20,
    paddingBottom: 20,
    paddingLeft: 20,
  },
  menuItem: {width: '25%', alignItems: 'center', marginTop: 14},
  btnBox: {position: 'absolute', bottom: 40, width: '100%'},
  btnWrap: {
    marginTop: 10,
    marginRight: 20,
    marginBottom: 10,
    marginLeft: 20,
    borderRadius: 10,
    backgroundColor: '#005cef',
  },
  btn: {textAlign: 'center', fontSize: 16, lineHeight: 48, color: 'white'},
  menuImage: {backgroundColor: '#fff', width: 54, height: 54},
  menuLabel: {color: '#333333', marginTop: 6, fontSize: 14, fontWeight: '500'},
  card: {
    paddingTop: 0,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    backgroundColor: 'white',
    borderRadius: 10,
    marginTop: 14,
  },
  productItem: {
    backgroundColor: 'white',
    borderRadius: 10,
    marginTop: 14,
    marginLeft: 14,
    marginRight: 14,
    paddingTop: 8,
    paddingRight: 8,
    paddingBottom: 8,
    paddingLeft: 8,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
  },
  productImage: {width: 80, height: 80, marginRight: 8},
  productTitle: {color: '#303133'},
  productLabel: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row', marginTop: 4},
  productSlogan: {color: '#E73A32', borderRadius: 4, height: 18, lineHeight: 18},
  productBottom: {
    marginTop: 12,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  productPrice: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row'},
  productBuy: {
    minWidth: 50,
    backgroundColor: '#E73A32',
    height: 20,
    borderRadius: 10,
    color: 'white',
    textAlign: 'center',
    lineHeight: 20,
  },
  productPricePrefix: {fontSize: 12, color: '#E73A32', paddingTop: 3},
  productPriceNum: {color: '#E73A32', fontWeight: 'bold'},
  page: {backgroundColor: '#f7f7f7'},
  center: {flexGrow: 1, flexShrink: 1, flexBasis: 0, alignItems: 'center', justifyContent: 'center'},
  button: {height: 40, marginTop: 14, marginRight: 14, marginBottom: 14, marginLeft: 14, borderRadius: 20},
  buttonText: {color: 'white', textAlign: 'center', lineHeight: 40, fontSize: 14},
  configPage: {flexGrow: 1, flexShrink: 1, flexBasis: 0, justifyContent: 'space-between'},
  listButton: {width: 50, height: 30, marginRight: 0},
  listThumb: {width: 40, height: 40, borderRadius: 20, marginRight: 8},
  selectPicture: {
    width: 100,
    height: 100,
    lineHeight: 100,
    textAlign: 'center',
    fontSize: 30,
    color: '#DCDFE6',
    borderWidth: 1,
    borderColor: '#DCDFE6',
    borderStyle: 'solid',
    borderRadius: 6,
    marginLeft: 8,
    marginTop: 8,
  },
  spec: {color: '#9E9E9E', paddingTop: 4},
  bg: {height: '100%', backgroundColor: '#f2f3f3'},
  lineThrough: {textDecorationLine: 'line-through', textDecorationColor: 'white', textDecorationStyle: 'solid'},
  back: {
    flexDirection: 'row',
    alignItems: 'center',
    top: 40,
    left: 20,
    position: 'absolute',
    backgroundColor: 'rgba(51, 51, 51, 0.5)',
    zIndex: 10,
    width: 30,
    height: 30,
    borderRadius: 30,
    paddingTop: 0,
    paddingRight: 8,
    paddingBottom: 0,
    paddingLeft: 8,
  },
  btn3: {marginTop: 30, marginRight: 10, marginBottom: 30, marginLeft: 10, textAlign: 'center', borderRadius: 5},
  btn2Content: {
    paddingTop: 14,
    paddingBottom: 14,
    fontWeight: '800',
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
  },
  applyBtn: {marginTop: 40, marginRight: 'auto', marginBottom: 0, marginLeft: 'auto'},
  applyBtnText: {color: '#fff', lineHeight: 44, width: 300, fontSize: 18, fontWeight: 'bold', textAlign: 'center'},
  codeTitle: {marginTop: 10, fontSize: 28, paddingTop: 14, paddingRight: 14, paddingBottom: 10, paddingLeft: 14},
  codePhone: {
    marginTop: 10,
    color: '#222',
    fontSize: 16,
    paddingTop: 0,
    paddingRight: 14,
    paddingBottom: 0,
    paddingLeft: 14,
  },
  'clamp-1': {
    wordBreak: 'break-all',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 1,
    overflow: 'hidden',
  },
  cell: {paddingTop: 16, paddingRight: 0, paddingBottom: 16, paddingLeft: 0, flexDirection: 'row'},
  cellBorder: {borderBottomWidth: 1, borderBottomColor: '#ebedf0'},
  between: {justifyContent: 'space-between', alignItems: 'center'},
  textInput: {minWidth: 200},
  left: {minWidth: 80},
  footer: {width: '100%', backgroundColor: '#fff', position: 'absolute', bottom: 0, paddingBottom: 20},
  footerRemind: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
  },
  protocol: {textDecorationLine: 'underline', textDecorationColor: 'black', textDecorationStyle: 'solid'},
  inputBox: {paddingTop: 0, paddingRight: 20, paddingBottom: 20, paddingLeft: 20},
  modalBox: {width: '80%', maxHeight: '60%', zIndex: 1, backgroundColor: '#fff', borderRadius: 6},
}
