module.exports = {
  userArea: {
    position: 'relative',
    zIndex: 10,
    marginTop: 5,
    marginRight: 0,
    marginBottom: 5,
    marginLeft: 0,
    height: 48,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 10,
    borderRadius: 8,
    backgroundColor: '#fff',
  },
  userWrap: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%'},
  userLeft: {flexDirection: 'row', alignItems: 'center'},
  userRight: {flexDirection: 'row', alignItems: 'center'},
  nickname: {maxWidth: 70, color: '#3A3A3A', fontWeight: '500', height: 16, lineHeight: 16, fontSize: 15},
  levelWrap: {
    alignSelf: 'flex-start',
    backgroundColor: '#ff4a4a',
    borderRadius: 12,
    fontSize: 12,
    paddingTop: 0,
    paddingRight: 5,
    paddingBottom: 0,
    paddingLeft: 5,
    marginLeft: 10,
    fontWeight: '400',
    lineHeight: 24,
    color: '#fff',
    overflow: 'hidden',
  },
  menuBox: {
    paddingTop: 12,
    paddingRight: 12,
    paddingBottom: 12,
    paddingLeft: 12,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  pointLabel: {textAlign: 'center', color: '#9E9E9E', fontSize: 12},
  pointIcon: {width: 18, height: 18},
  unit: {color: '#3A3A3A', marginTop: 0, marginRight: 5, marginBottom: 0, marginLeft: 5},
  unitLevel: {color: '#FF2050', fontSize: 12},
  point: {color: '#3A3A3A', fontSize: 24, fontWeight: 'bold', textAlign: 'center'},
  infoText: {fontSize: 13, fontWeight: '400', color: '#FF4A4A', lineHeight: 18, marginLeft: 12},
  coupon: {
    height: 20,
    fontSize: 13,
    paddingTop: 4,
    paddingRight: 15,
    paddingBottom: 4,
    paddingLeft: 15,
    fontWeight: 'bold',
    borderRadius: 30,
    lineHeight: 20,
    textAlign: 'center',
    backgroundColor: '#FF2A41',
    color: '#3A3A3A',
  },
  specialSpu: {
    position: 'relative',
    backgroundColor: '#fff',
    borderRadius: 20,
    marginTop: 24,
    marginRight: 14,
    marginBottom: 14,
    marginLeft: 14,
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
  },
  activeText: {color: '#fe733b'},
  productName: {fontSize: 15, marginTop: 10},
  price: {marginTop: 10},
  buyIcon: {position: 'absolute', bottom: 14, right: 14},
  middleBanner: {
    width: '100%',
    boxSizing: 'border-box',
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
  },
  middleBannerImage: {width: '100%', borderRadius: 10},
  freeMallPage: {height: '100%', width: '100%', backgroundColor: '#fff'},
  menuIcon: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center'},
  input: {width: '100%', backgroundColor: '#fff'},
  showImg: {marginTop: 20, marginRight: 20, marginBottom: 20, marginLeft: 20},
  eachImage: {borderRadius: 15},
  listBox: {
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    backgroundColor: '#fff',
    color: '#888',
    marginTop: 20,
    marginRight: 20,
    marginBottom: 15,
    marginLeft: 20,
    borderRadius: 10,
  },
  listTitle: {flexDirection: 'row', alignItems: 'center'},
  listText: {
    fontSize: 20,
    paddingTop: 5,
    paddingRight: 0,
    paddingBottom: 5,
    paddingLeft: 0,
    fontWeight: 'bold',
    color: '#222222',
    lineHeight: 38,
  },
  list: {width: '100%', height: 120, overflow: 'hidden', position: 'relative'},
  listWrap: {position: 'absolute'},
  free: {backgroundColor: '#f8f8f8'},
  buy: {backgroundColor: '#f1fcfa'},
  listItem: {
    width: '100%',
    height: 32,
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
    flexDirection: 'row',
    alignItems: 'center',
    fontSize: 11,
    borderRadius: 16,
    color: '#222222',
  },
  avatar: {width: 24, height: 24, borderRadius: 12, flexShrink: 0},
  desc: {marginLeft: 10, lineHeight: 20},
  noInfo: {paddingTop: 20, paddingRight: 0, paddingBottom: 20, paddingLeft: 0},
  noInfoText: {textAlign: 'center', fontSize: 12, color: '#222222'},
  selectionItem: {marginTop: 0, marginRight: 10, marginBottom: 0, marginLeft: 10},
  selectionTitle: {color: '#9E9E9E', fontSize: 14},
  selectedTitle: {color: '#222222', fontSize: 16, fontWeight: 'bold', marginTop: -2},
  selectionSubTitle: {color: '#FA632C', fontSize: 12},
  textInput: {
    width: '100%',
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  searchWrap: {
    backgroundColor: '#F7F7F7',
    borderRadius: 2,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    marginRight: 22,
    marginBottom: 12,
    marginLeft: 22,
    paddingTop: 8,
    paddingRight: 4,
    paddingBottom: 8,
    paddingLeft: 4,
  },
  menuImage: {width: 50, height: 50},
  menuLabel: {textAlign: 'center', fontSize: 10, fontWeight: '400', color: '#333333', lineHeight: 14},
  modalBox: {
    paddingTop: 10,
    paddingBottom: 10,
    width: '100%',
    backgroundColor: '#fff',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  tabItem: {
    display: 'flex',
    marginTop: 15,
    marginRight: 10,
    marginBottom: 0,
    marginLeft: 10,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 12,
    borderWidth: 1,
    borderColor: '#eee',
    backgroundColor: '#eee',
  },
  menuTitle: {color: '#333333', marginTop: 6, fontSize: 12, fontWeight: '400'},
  active: {borderWidth: 1, borderColor: '#fe733b', backgroundColor: '#fff'},
  tabText: {lineHeight: 24},
  freeTag: {
    backgroundColor: '#FF2A41',
    alignSelf: 'flex-start',
    color: '#fff',
    lineHeight: 14,
    fontSize: 10,
    paddingTop: 0,
    paddingRight: 3,
    paddingBottom: 0,
    paddingLeft: 3,
    borderRadius: 2,
    overflow: 'hidden',
  },
  storeInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(210, 177, 134, 0.2)',
    color: '#3A3A3A',
    paddingTop: 7,
    paddingRight: 0,
    paddingBottom: 7,
    paddingLeft: 13,
    fontSize: 12,
  },
  zone: {
    marginTop: 10,
    marginRight: 16,
    marginBottom: 10,
    marginLeft: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  zoneItem: {
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 11,
    paddingRight: 8,
    paddingBottom: 11,
    paddingLeft: 8,
    borderRadius: 10,
    position: 'relative',
  },
  label: {fontSize: 14, fontWeight: '400', color: '#3A3A3A', lineHeight: 20},
  tip: {marginTop: 5, fontSize: 11, fontWeight: '400', color: '#898989', lineHeight: 16},
  'right-item': {position: 'absolute', right: 8},
  btn: {
    lineHeight: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    borderStyle: 'solid',
    fontSize: 11,
    fontWeight: '400',
    color: '#3A3A3A',
    overflow: 'hidden',
    paddingTop: 0,
    paddingRight: 6,
    paddingBottom: 0,
    paddingLeft: 6,
  },
  color1: {backgroundColor: '#FFE2A7'},
  color2: {backgroundColor: '#FFDCCA'},
  levelProductWrap: {marginTop: 10, marginRight: 0, marginBottom: 0, marginLeft: 0},
  levelProduct: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 0,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
  },
  levelItem: {
    height: 82,
    width: 107,
    borderWidth: 1,
    borderColor: '#E9E9E9',
    borderStyle: 'solid',
    borderRadius: 6,
    position: 'relative',
    marginRight: 10,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelItemText: {fontWeight: '500', fontSize: 22, color: '#FF5F70', textAlign: 'center'},
  activeLevel: {borderColor: '#FF4A4A'},
  activeIcon: {position: 'absolute', top: 0, right: 0, opacity: 0, width: 25, height: 25},
  iconActive: {opacity: 1},
  levelBtn: {marginTop: 13, borderRadius: 20, marginBottom: 14},
  levelText: {color: '#fff', fontWeight: '500', fontSize: 14, textAlign: 'center', lineHeight: 40},
  levelTitleText: {
    fontSize: 18,
    fontWeight: '500',
    marginTop: 5,
    color: '#FF4A4A',
    lineHeight: 25,
    textAlign: 'center',
  },
}
