module.exports = {
  searchWrap: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
    paddingTop: 0,
    paddingRight: 14,
    paddingBottom: 0,
    paddingLeft: 14,
  },
  searchBox: {flexDirection: 'row', alignItems: 'center', paddingRight: 14},
  searchSuggestHeader: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 20, marginBottom: 14},
  searchItemList: {flexDirection: 'row', flexWrap: 'wrap'},
  li: {
    backgroundColor: '#f7f7f7',
    color: '#737373',
    paddingTop: 4,
    paddingRight: 6,
    paddingBottom: 4,
    paddingLeft: 6,
    marginRight: 10,
    marginBottom: 10,
    borderRadius: 4,
    overflow: 'hidden',
  },
  toast: {color: '#3A3A3A'},
}
