module.exports = {
  slideWrapper: {position: 'relative'},
  slideNumBox: {position: 'absolute', bottom: 10, right: 20, backgroundColor: 'rgba(0, 0, 0, 0.2)', borderRadius: 20},
  slideNum: {fontSize: 12, color: '#fff', height: 30, lineHeight: 30, width: 30, textAlign: 'center'},
  freeTag: {
    paddingTop: 1,
    paddingRight: 4,
    paddingBottom: 1,
    paddingLeft: 4,
    fontSize: 12,
    color: '#fff',
    overflow: 'hidden',
  },
  item: {marginTop: 16, marginRight: 16, marginBottom: 0, marginLeft: 16, borderRadius: 8},
  serverPanel: {backgroundColor: '#ffffff', overflow: 'hidden'},
  freeTagBox: {backgroundColor: '#FF4A4A', borderRadius: 4},
  updatedAt: {marginTop: 8, fontSize: 12, fontWeight: '400', color: '#999', lineHeight: 14},
  advertise: {marginTop: 4, fontSize: 14, fontWeight: '400', color: '#999999', lineHeight: 20},
  headerCard: {backgroundColor: 'white', paddingTop: 4, paddingRight: 14, paddingBottom: 20, paddingLeft: 14},
  countWrap: {height: 30},
  priceWrapper: {height: 24, marginTop: 10, flexDirection: 'row', justifyContent: 'space-between'},
  price: {
    paddingTop: 10,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  priceText: {flexDirection: 'row', alignItems: 'flex-end', fontWeight: '600'},
  collection: {textAlign: 'center', color: '#9E9E9E', minWidth: 30, marginTop: 4, fontSize: 10},
  priceBox: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row', alignItems: 'baseline'},
  originalPrice: {paddingLeft: 10, color: '#ababab', fontSize: 12},
  flashOriginalPrice: {
    marginLeft: 10,
    textDecorationLine: 'line-through',
    textDecorationColor: 'white',
    textDecorationStyle: 'solid',
    color: 'white',
  },
  unit: {color: '#E73A32', fontWeight: 'bold'},
  yuan: {color: '#E73A32', fontSize: 30, fontWeight: 'bold'},
  fen: {color: '#E73A32', fontWeight: 'bold'},
  title: {lineHeight: 20, marginTop: 10, color: 'black', fontSize: 16, fontWeight: 'bold'},
  description: {
    lineHeight: 18,
    marginTop: 8,
    marginRight: 0,
    marginBottom: 8,
    marginLeft: 0,
    color: '#9E9E9E',
    fontSize: 14,
  },
  descriptionCoin: {
    lineHeight: 18,
    marginTop: 4,
    marginRight: 0,
    marginBottom: 4,
    marginLeft: 0,
    color: '#9E9E9E',
    fontSize: 14,
  },
  operator: {left: 0, bottom: 0, width: '100%', backgroundColor: 'white'},
  operatorBox: {
    height: 60,
    paddingTop: 8,
    paddingRight: 14,
    paddingBottom: 8,
    paddingLeft: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  icon: {
    flexShrink: 0,
    width: 40,
    alignItems: 'center',
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
  },
  starIcon: {
    flexShrink: 0,
    width: 40,
    alignItems: 'center',
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
  },
  txt: {fontSize: 12, textAlign: 'center'},
  sales: {marginTop: 8, color: '#9E9E9E'},
  iconCenter: {marginTop: 0, marginRight: 'auto', marginBottom: 0, marginLeft: 'auto'},
  listItem: {
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    paddingRight: 12,
    paddingBottom: 12,
    paddingLeft: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f7f7f7',
  },
  listTitle: {width: 50, color: '#9E9E9E', fontSize: 14},
  listLine: {color: '#eee', marginTop: 0, marginRight: 4, marginBottom: 0, marginLeft: 4},
  listContent: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    width: '100%',
    textAlign: 'left',
    fontSize: 14,
    color: '#3A3A3A',
  },
  serviceImage: {marginTop: 2, width: 12, height: 12},
  serviceItem: {flexDirection: 'row', marginRight: 12, marginBottom: 6, color: '#3A3A3A'},
  serviceName: {color: '#3A3A3A'},
  right: {width: 20},
  commentWrap: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    paddingTop: 12,
    paddingRight: 12,
    paddingBottom: 12,
    paddingLeft: 12,
  },
  commentHeader: {
    width: '100%',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  couponLabel: {color: '#fff', fontWeight: 'bold'},
  couponView: {
    wordBreak: 'keep-all',
    height: 18,
    lineHeight: 18,
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
    backgroundColor: '#feeee8',
    borderRadius: 4,
    marginRight: 10,
  },
  couponText: {color: '#E73A32'},
  commentBox: {
    backgroundColor: '#ffffff',
    paddingTop: 10,
    paddingRight: 0,
    paddingBottom: 10,
    paddingLeft: 0,
    marginTop: 12,
  },
  commentInfo: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  commentLeft: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  time: {color: '#9E9E9E'},
  commentAvatar: {height: 40, width: 40, borderWidth: 1, borderColor: '#eee', borderRadius: 40, marginRight: 14},
  commentNickname: {fontSize: 14, fontWeight: '400', color: '#3A3A3A', lineHeight: 20},
  timeLabel: {fontSize: 12, fontWeight: '400', color: '#989898', lineHeight: 17},
  commentContent: {paddingTop: 14, paddingRight: 0, paddingBottom: 14, paddingLeft: 0, fontSize: 16},
  images: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row'},
  moreText: {textAlign: 'center', lineHeight: 50, color: '#3A3A3A'},
  tenantAvatar: {height: 50, width: 50, borderRadius: 8, marginRight: 14},
  tenantInfo: {marginTop: 14, backgroundColor: '#ffffff', overflow: 'hidden'},
  tenantBox: {flexDirection: 'row', paddingTop: 14, paddingRight: 14, paddingBottom: 14, paddingLeft: 14},
  tenantLeft: {flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row'},
  tenantNickname: {color: '#3A3A3A', fontSize: 18, fontWeight: 'bold'},
  btnWrap: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
  },
  tenantRate: {width: 180, flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row', color: '#9E9E9E'},
  tenantBtnText: {textAlign: 'center', fontSize: 14, lineHeight: 26, color: '#E73A32'},
  skuSelector: {width: '100%', height: '100%'},
  skuImage: {borderRadius: 4, width: 100, height: 100},
  headText: {paddingTop: 0, paddingRight: 14, paddingBottom: 0, paddingLeft: 14},
  select: {marginTop: 6, flexGrow: 1, flexShrink: 1, flexBasis: 0, flexDirection: 'row', alignItems: 'flex-start'},
  stock: {marginTop: 6, color: '#9E9E9E'},
  selected: {marginRight: 6, color: '#9E9E9E'},
  spec: {alignItems: 'flex-start'},
  specUl: {flexDirection: 'row', flexWrap: 'wrap'},
  specName: {marginTop: 10, color: '#9E9E9E'},
  specLi: {
    flexWrap: 'wrap',
    paddingTop: 5,
    paddingRight: 12,
    paddingBottom: 5,
    paddingLeft: 12,
    backgroundColor: '#f2f3f5',
    borderRadius: 25,
    marginRight: 10,
    marginTop: 10,
  },
  specLiText: {textAlign: 'center', minWidth: 30},
  countSku: {marginTop: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  skuButton: {
    width: '100%',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    position: 'absolute',
    bottom: 20,
    left: 0,
    height: 60,
  },
  buttonText: {textAlign: 'center', lineHeight: 60, fontWeight: 'bold', color: '#ffffff'},
  active: {color: '#f85824'},
  activeLi: {backgroundColor: 'rgba(248, 88, 36, 0.08)'},
  inactive: {color: '#ababab'},
  default: {color: '#3A3A3A'},
  likeTitle: {
    paddingTop: 20,
    paddingRight: 0,
    paddingBottom: 20,
    paddingLeft: 0,
    textAlign: 'center',
    fontSize: 16,
    color: '#3A3A3A',
  },
  productSwiper: {backgroundColor: '#fff', paddingTop: 16, paddingRight: 9, paddingBottom: 16, paddingLeft: 9},
  lineWrap: {
    marginTop: 14,
    marginRight: 0,
    marginBottom: 14,
    marginLeft: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  line: {
    width: 100,
    height: 1,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    marginTop: 14,
    marginRight: 14,
    marginBottom: 14,
    marginLeft: 14,
  },
  lineTitle: {color: '#9E9E9E'},
  attributeWrap: {
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  attributeName: {width: '30%', paddingTop: 10, paddingRight: 10, paddingBottom: 10, paddingLeft: 10, color: '#3A3A3A'},
  attributeValue: {
    width: '70%',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    color: '#3A3A3A',
    marginLeft: -1,
  },
  bottomTip: {textAlign: 'center', marginTop: 14, marginRight: 14, marginBottom: 14, marginLeft: 14, color: '#9E9E9E'},
  articleWrap: {backgroundColor: '#fff', paddingTop: 14, paddingRight: 14, paddingBottom: 14, paddingLeft: 14},
  mineDotWrap: {position: 'absolute', top: -8, right: 0, backgroundColor: '#ea0c25', borderRadius: 10, minWidth: 16},
  mineDot: {
    color: '#fff',
    textAlign: 'center',
    paddingTop: 0,
    paddingRight: 2,
    paddingBottom: 0,
    paddingLeft: 2,
    fontSize: 14,
  },
  linearBtnWrap: {borderRadius: 20},
  linearBtn: {color: 'white', paddingTop: 12, textAlign: 'center', paddingBottom: 12, fontWeight: '900', fontSize: 16},
  flashSalWrapper: {
    flexDirection: 'row',
    backgroundColor: '#FF4A4A',
    paddingTop: 10,
    paddingRight: 0,
    paddingBottom: 10,
    paddingLeft: 0,
  },
  menuBox: {flexDirection: 'row', alignItems: 'center'},
  collectionItem: {textAlign: 'center', flexDirection: 'column', alignItems: 'center'},
  flashSaleLabel: {color: '#fff', fontSize: 18, fontWeight: 'bold', marginLeft: 14},
  countDownWrap: {flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', paddingRight: 10},
  leafTag: {
    backgroundColor: '#E73A32',
    paddingTop: 0,
    paddingRight: 2,
    paddingBottom: 0,
    paddingLeft: 2,
    color: '#fff',
    borderRadius: 4,
    overflow: 'hidden',
  },
  rateLabel: {color: '#9E9E9E', fontSize: 12},
  couponArea: {marginTop: 10, flexDirection: 'row', justifyContent: 'space-between'},
  couponLeft: {flexDirection: 'row'},
  couponItem: {
    backgroundColor: '#fae9ea',
    paddingTop: 2,
    paddingRight: 2,
    paddingBottom: 2,
    paddingLeft: 2,
    color: '#E73A32',
    fontSize: 12,
    borderRadius: 4,
    marginRight: 8,
  },
  couponRight: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    borderLeftWidth: 1,
    borderLeftColor: '#d8d8d8',
    paddingLeft: 12,
  },
  couponRightText: {fontSize: 12, color: '#E73A32'},
  share1: {
    position: 'absolute',
    left: '82%',
    top: 410,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    zIndex: 20,
  },
  share2: {
    position: 'absolute',
    left: '82%',
    top: 460,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    zIndex: 20,
  },
  shareImage: {width: 40, height: 40},
  searchWrap: {
    backgroundColor: '#ffffff',
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 22,
    paddingTop: 8,
    paddingRight: 4,
    paddingBottom: 8,
    paddingLeft: 4,
  },
  bottomMenu: {flexDirection: 'row', alignItems: 'center', marginTop: 17},
  rateWrap: {flexDirection: 'column', alignItems: 'flex-end'},
  rateStarLabel: {fontSize: 11, fontWeight: '400', color: '#9E9E9E', lineHeight: 16, marginLeft: 3},
  rate: {flexDirection: 'row', alignItems: 'center'},
  high: {color: '#FC7779'},
  low: {color: '#67C23A'},
  tenantMenu: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 22,
    paddingRight: 0,
    paddingBottom: 22,
    paddingLeft: 0,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(137, 137, 137, 0.1)',
  },
  tenantBtn: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#FB6D6D',
    borderStyle: 'solid',
    lineHeight: 28,
    borderRadius: 14,
    fontSize: 14,
    fontWeight: '400',
    color: '#FB6D6D',
    paddingTop: 0,
    paddingRight: 12,
    paddingBottom: 0,
    paddingLeft: 12,
    marginTop: 0,
    marginRight: 7,
    marginBottom: 0,
    marginLeft: 7,
  },
  myNav: {position: 'absolute', top: 0, width: '100%', zIndex: 100, backgroundColor: '#F5F5F5'},
  navBox: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  tenantLevel: {
    marginTop: 4,
    backgroundColor: '#FF5D60',
    borderRadius: 3,
    overflow: 'hidden',
    paddingTop: 1,
    paddingRight: 2,
    paddingBottom: 1,
    paddingLeft: 2,
    fontSize: 10,
    fontWeight: '400',
    color: '#fff',
    lineHeight: 14,
    alignSelf: 'flex-start',
  },
  modalBox: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
    overflow: 'hidden',
  },
  btnBox: {position: 'absolute', backgroundColor: '#fff', paddingBottom: 20, bottom: 0, width: '100%'},
  bottomBtnWrap: {borderRadius: 20, marginTop: 0, marginRight: 20, marginBottom: 0, marginLeft: 20},
  bottomBtn: {textAlign: 'center', fontSize: 16, lineHeight: 40, color: 'white'},
}
