module.exports = {
  shopDetailPage: {backgroundColor: '#f8f8f8', height: '100%'},
  item: {
    transform: [{translateY: -30}],
    marginTop: 0,
    marginRight: 0,
    marginBottom: 20,
    marginLeft: 0,
    backgroundColor: '#fff',
    borderRadius: 15,
    position: 'relative',
  },
  menuBox: {position: 'absolute', flexDirection: 'row', right: 15, top: -19},
  shopTitle: {
    marginTop: 20,
    paddingTop: 0,
    paddingRight: 15,
    paddingBottom: 0,
    paddingLeft: 15,
    color: '#3A3A3A',
    lineHeight: 28,
    fontSize: 18,
    fontWeight: 'bold',
  },
  wrap: {
    marginTop: 0,
    marginRight: 15,
    marginBottom: 0,
    marginLeft: 15,
    paddingTop: 15,
    paddingRight: 0,
    paddingBottom: 15,
    paddingLeft: 0,
    position: 'relative',
  },
  flex: {flexDirection: 'row', justifyContent: 'space-between'},
  content: {width: '70%'},
  evaluationBox: {flexDirection: 'row', alignItems: 'center'},
  points: {marginLeft: 10, fontSize: 12, fontWeight: '400', color: '#808080'},
  evaluation: {fontSize: 12, fontWeight: '400', color: '#808080', marginLeft: 16},
  tagWrap: {marginTop: 10, flexDirection: 'row', alignItems: 'center'},
  tagLine: {
    width: 1,
    height: 8,
    marginTop: 0,
    marginRight: 5,
    marginBottom: 0,
    marginLeft: 5,
    backgroundColor: '#adadad',
  },
  tag: {fontSize: 12, fontWeight: '400', color: '#adadad'},
  right: {
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderStyle: 'solid',
    width: 66,
    height: 66,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  performance: {fontSize: 28, fontWeight: 'bold', color: '#3A3A3A'},
  performanceText: {fontSize: 11, fontWeight: '400', color: '#999999', lineHeight: 20},
  distance: {fontSize: 12, fontWeight: '400', color: '#999999'},
  name: {fontSize: 13, fontWeight: '400', lineHeight: 18, color: '#3A3A3A', marginBottom: 10},
  toThere: {
    flexDirection: 'row',
    alignItems: 'center',
    fontSize: 12,
    fontWeight: '400',
    flexShrink: 0,
    color: '#333333',
  },
  rank: {flexDirection: 'row', alignItems: 'center', fontSize: 12, fontWeight: '400', color: '#666666'},
  iconWrap: {
    transform: [{translateY: -30}],
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 0,
    marginRight: 20,
    marginBottom: 20,
    marginLeft: 20,
  },
  iconItem: {textAlign: 'center', flexDirection: 'column', justifyContent: 'center', alignItems: 'center'},
  label: {textAlign: 'center', fontWeight: '500', lineHeight: 27, fontSize: 11, color: '#222222'},
  colorPrimary: {backgroundColor: '#FA632C'},
  flashTitle: {flexDirection: 'row', alignItems: 'flex-end'},
  flashLabel: {fontSize: 18, fontWeight: 'bold', color: '#333333', marginRight: 9},
  finishText: {marginLeft: 5, fontSize: 12, fontWeight: '400', color: '#7E7E7E'},
  flashInfo: {
    fontSize: 12,
    fontWeight: '400',
    color: '#7E7E7E',
    marginTop: 15,
    marginRight: 0,
    marginBottom: 15,
    marginLeft: 0,
  },
  flashInfoTitle: {marginTop: 5, marginRight: 5, marginBottom: 5, marginLeft: 5, fontSize: 14, color: '#3A3A3A'},
  flashInfoDesc: {fontSize: 12, color: '#cecece'},
  flashProduct: {marginTop: 10, flexDirection: 'row'},
  productInfo: {marginLeft: 12},
  productTitle: {flexDirection: 'row', alignItems: 'center'},
  productTag: {width: 16, lineHeight: 16, textAlign: 'center', fontSize: 11, fontWeight: 'bold', color: '#FFFFFF'},
  productTagBox: {borderRadius: 5, backgroundColor: '#E92D2D', marginRight: 7},
  productLabel: {fontSize: 16, fontWeight: 'bold', color: '#333333', lineHeight: 20},
  progressWrap: {marginTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  progressBox: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    height: 10,
    borderColor: '#FF4A4A',
    position: 'relative',
    overflow: 'hidden',
  },
  progressItem: {position: 'absolute', height: 10, left: 0, backgroundColor: '#FF4A4A'},
  originalPrice: {
    textDecorationLine: 'line-through',
    textDecorationColor: 'black',
    textDecorationStyle: 'solid',
    color: '#9E9E9E',
    marginTop: 4,
  },
  priceWrap: {flexDirection: 'row', alignItems: 'center'},
  buyBtnBox: {width: 65, backgroundColor: '#F23A3A', borderRadius: 12},
  price: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10},
  buyBtn: {lineHeight: 24, textAlign: 'center', fontSize: 12, fontWeight: '500', color: '#FFFFFF'},
  bargainLabel: {fontSize: 18, fontWeight: 'bold', color: '#333333', marginRight: 9},
  bargainInfo: {
    fontSize: 12,
    fontWeight: '400',
    color: '#7E7E7E',
    marginTop: 15,
    marginRight: 0,
    marginBottom: 15,
    marginLeft: 0,
  },
  bargainItem: {
    paddingTop: 5,
    paddingRight: 5,
    paddingBottom: 5,
    paddingLeft: 5,
    flexDirection: 'column',
    alignItems: 'center',
    width: '33%',
  },
  bargainName: {marginTop: 14, fontSize: 15, fontWeight: '400', color: '#333333'},
  bargainBtnBox: {
    marginTop: 10,
    marginRight: 'auto',
    marginBottom: 10,
    marginLeft: 'auto',
    width: 92,
    backgroundColor: '#F23A3A',
    borderRadius: 12,
  },
  bargainBtn: {lineHeight: 24, textAlign: 'center', fontSize: 12, fontWeight: '500', color: '#FFFFFF'},
  appointmentItem: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12},
  spuContent: {flexDirection: 'row', alignItems: 'center'},
  spuInfo: {width: 180, marginLeft: 12},
  spuPrice: {fontSize: 15, fontWeight: 'bold', color: '#222222'},
  spuName: {fontSize: 14, fontWeight: '400', color: '#222222'},
  spuBtnBox: {width: 75, backgroundColor: '#FF2A41', borderRadius: 15},
  spuBtn: {lineHeight: 30, textAlign: 'center', color: 'white'},
  commentItem: {paddingTop: 20, paddingRight: 0, paddingBottom: 20, paddingLeft: 0},
  commentUser: {flexDirection: 'row', justifyContent: 'space-between'},
  userInfoWrap: {flexDirection: 'row'},
  nickName: {width: 150},
  date: {fontSize: 12, fontWeight: 'bold', color: '#B8BBC2'},
  emptyWrap: {
    textAlign: 'center',
    paddingTop: 20,
    paddingRight: 0,
    paddingBottom: 20,
    paddingLeft: 0,
    fontSize: 13,
    color: '#cecece',
  },
  commentTextBox: {marginTop: 20, lineHeight: 20},
  commentText: {fontSize: 14, fontWeight: '400', color: '#3A3A3A', marginTop: 20},
  commentImage: {marginTop: 20, flexWrap: 'wrap', flexDirection: 'row'},
  operator: {left: 0, bottom: 60, width: '100%', backgroundColor: 'white'},
  operatorBox: {
    height: 60,
    paddingTop: 8,
    paddingRight: 5,
    paddingBottom: 8,
    paddingLeft: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  icon: {
    flexShrink: 0,
    width: 40,
    alignItems: 'center',
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
  },
  txt: {marginTop: 4, fontSize: 10, color: '#9E9E9E'},
}
