module.exports = {
  shopListPage: {backgroundColor: '#f7f7f7', height: '100%'},
  shopLocation: {
    flexDirection: 'row',
    fontWeight: '500',
    alignItems: 'center',
    marginTop: 20,
    marginRight: 20,
    marginBottom: 0,
    marginLeft: 20,
    paddingTop: 20,
    paddingRight: 22,
    paddingBottom: 20,
    paddingLeft: 22,
    borderRadius: 15,
    backgroundColor: '#fff',
  },
  locationText: {textAlign: 'center', color: '#222', fontWeight: 'bold', fontSize: 15},
  iconWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 20,
    paddingBottom: 0,
    paddingLeft: 20,
  },
  locationImage: {width: 18, height: 22, marginRight: 10},
  iconImage: {width: 50, height: 50, borderRadius: 25},
  label: {textAlign: 'center', marginTop: 10},
  shop: {
    backgroundColor: '#fff',
    marginTop: 20,
    marginRight: 20,
    marginBottom: 0,
    marginLeft: 20,
    borderBottom: '0 solid #eee',
    paddingTop: 15,
    paddingRight: 0,
    paddingBottom: 15,
    paddingLeft: 15,
    borderRadius: 15,
    flexDirection: 'row',
    boxSizing: 'border-box',
    justifyContent: 'space-between',
    position: 'relative',
  },
  shopAvatar: {width: 80, height: 80, borderRadius: 8},
  content: {width: '70%', paddingTop: 0, paddingRight: 10, paddingBottom: 0, paddingLeft: 10},
  nameWrap: {
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#3A3A3A',
  },
  footer: {
    fontSize: 14,
    color: '#999999',
    paddingTop: 0,
    paddingRight: 4,
    paddingBottom: 0,
    paddingLeft: 4,
    marginTop: 10,
    marginRight: 0,
    marginBottom: 16,
    marginLeft: 0,
  },
  infoBox: {flexDirection: 'row', justifyContent: 'space-between'},
  phone: {flexDirection: 'row', alignItems: 'center'},
  phoneImage: {width: 18, height: 18, marginRight: 4},
  phoneText: {color: '#9E9E9E', fontSize: 14, fontWeight: '500'},
  distance: {flexDirection: 'row', alignItems: 'center'},
  distanceImage: {width: 18, height: 18, marginRight: 4},
  distanceText: {color: '#ababab', fontSize: 14, fontWeight: '500'},
}
