module.exports = {
  shopData: {backgroundColor: '#EDEDED', height: '100%'},
  dataCard: {
    marginTop: 10,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingTop: 18,
    paddingRight: 18,
    paddingBottom: 18,
    paddingLeft: 18,
  },
  rateBox: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: 108,
    boxSizing: 'border-box',
    marginTop: 5,
    marginBottom: 5,
    height: 17,
    borderRadius: 9,
  },
  btnText: {textAlign: 'center', height: 20, fontSize: 14, fontWeight: '600', color: '#FC7171', lineHeight: 20},
  stars: {marginTop: 11, fontSize: 11, fontWeight: '400', color: '#333333', lineHeight: 16},
  follow: {marginLeft: 'auto'},
  tenantName: {width: 150, fontSize: 16, fontWeight: '400', color: '#333333', lineHeight: 22},
  fans: {marginTop: 12, marginLeft: 3, width: 100, fontSize: 13, fontWeight: '400', color: '#9C9C9C', lineHeight: 18},
  starsInfo: {marginTop: 7, fontSize: 12, fontWeight: '400', color: '#9C9C9C', lineHeight: 17},
  rateList: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 18,
  },
  rateLabel: {fontSize: 11, fontWeight: '400', color: '#3A3A3A', lineHeight: 20, overflow: 'visible', marginRight: 5},
  progressBar: {height: 12, backgroundColor: '#FB6D6D', borderRadius: 7},
  rateNum: {fontSize: 15, fontWeight: '600', color: '#FC7171', lineHeight: 21},
  rateHigher: {fontSize: 11, fontWeight: '400', color: '#999999', lineHeight: 16},
  progress: {width: 120, height: 12, backgroundColor: '#F2F2F2', borderRadius: 7},
  avatarBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    display: 'flex',
    alignItems: 'center',
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F2',
  },
  'rate-box': {
    display: 'flex',
    alignItems: 'center',
    width: 108,
    boxSizing: 'border-box',
    marginTop: 5,
    marginBottom: 5,
    height: 17,
    borderRadius: 9,
  },
}
