module.exports = {
  walletPage: {backgroundColor: '#F8F8F8', height: '100%'},
  cardBox: {paddingTop: 20, paddingRight: 20, paddingBottom: 20, paddingLeft: 20, backgroundColor: '#fff'},
  cardWrap: {color: '#3A3A3A', borderRadius: 15, paddingTop: 0, paddingRight: 0, paddingBottom: 0, paddingLeft: 10},
  local: {fontSize: 15, fontWeight: '400', color: '#3A3A3A', lineHeight: 21},
  topics: {
    marginLeft: 15,
    marginBottom: 10,
    boxSizing: 'border-box',
    borderWidth: 1,
    borderColor: '#d0d4d7',
    borderStyle: 'solid',
    borderRadius: 40,
    backgroundColor: '#fff',
  },
  zoneBtn: {
    width: 110,
    height: 35,
    lineHeight: 35,
    color: '#fff',
    backgroundColor: '#96a7b5',
    textAlign: 'center',
    borderRadius: 35,
    marginBottom: 15,
  },
  brandListName: {zIndex: 1, color: '#FFFFFF', fontWeight: '700', fontSize: 22},
  topicsText: {lineHeight: 40, color: '#666666', textAlign: 'center'},
  content: {paddingBottom: 20, flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap'},
  price: {fontSize: 35, fontWeight: '400', color: '#3A3A3A', lineHeight: 49},
  unit: {fontSize: 25},
  priceBtnBox: {borderRadius: 13, width: 68},
  priceBtn: {lineHeight: 28, textAlign: 'center', fontSize: 14, fontWeight: '500', color: '#FFFFFF'},
  menu: {
    marginTop: 5,
    width: 70,
    lineHeight: 24,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    borderStyle: 'solid',
    textAlign: 'center',
    color: '#666666',
    fontSize: 12,
  },
  infoBox: {
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 20,
    paddingLeft: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 14,
    marginRight: 14,
    marginBottom: 10,
    marginLeft: 14,
    backgroundColor: '#fff',
    borderRadius: 15,
  },
  infoItem: {textAlign: 'center'},
  line: {height: 48, width: 1, backgroundColor: '#fff'},
  label: {
    fontSize: 14,
    fontWeight: '400',
    color: '#3A3A3A',
    lineHeight: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconImage: {width: 16, height: 16, marginRight: 4},
  labelText: {textAlign: 'center'},
  value: {fontSize: 15, fontWeight: '600', lineHeight: 21, marginTop: 6, color: '#3A3A3A', textAlign: 'center'},
  consumptionList: {paddingTop: 0, paddingRight: 14, paddingBottom: 0, paddingLeft: 14},
  consumptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eeeeee',
    paddingTop: 14,
    paddingRight: 0,
    paddingBottom: 14,
    paddingLeft: 0,
  },
  consumptionImage: {marginRight: 10, width: 30, height: 30},
  consumptionText: {fontSize: 15, fontWeight: '500', color: '#3A3A3A'},
  remark: {
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 13,
    color: '#777777',
    lineHeight: 18,
    paddingTop: 70,
    paddingRight: 0,
    paddingBottom: 40,
    paddingLeft: 0,
  },
}
