export const ANIMATE_ID = {
  BOUNCE: 'Bounce',
  FLASH: 'Flash',
  PULSE: 'Pulse',
  RUBBER_BAND: 'RubberBand',
  SHAKE_X: 'ShakeX',
  SHAKE_Y: 'ShakeY',
  HEAD_SHAKE: 'HeadShake',
  SWING: 'Swing',
  TADA: 'Tada',
  WOBBLE: 'Wobble',
  JELLO: 'Jello',
  HEART_BEAT: 'HeartBeat',
  BACK_IN_DOWN: 'BackInDown',
  BACK_IN_LEFT: 'BackInLeft',
  BACK_IN_RIGHT: 'BackInRight',
  BACK_IN_UP: 'BackInUp',
  BACK_OUT_DOWN: 'BackOutDown',
  BACK_OUT_LEFT: 'BackOutLeft',
  BACK_OUT_RIGHT: 'BackOutRight',
  BACK_OUT_UP: 'BackOutUp',
}
