module.exports = {
  pageBox: {backgroundColor: '#f8f8f8', height: '100%'},
  tip: {textAlign: 'center', paddingTop: 20, paddingRight: 20, paddingBottom: 20, paddingLeft: 20, color: '#666666'},
  itemTitle: {color: '#3A3A3A', fontWeight: '500', marginBottom: 10},
  itemLabel: {lineHeight: 24, color: '#3A3A3A'},
  redItem: {color: '#f85824'},
  item: {
    marginTop: 0,
    marginRight: 20,
    marginBottom: 0,
    marginLeft: 20,
    backgroundColor: '#fff',
    borderRadius: 8,
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 20,
    paddingLeft: 20,
  },
  footer: {
    width: '100%',
    backgroundColor: '#fff',
    position: 'absolute',
    bottom: 0,
    paddingTop: 20,
    paddingRight: 0,
    paddingBottom: 20,
    paddingLeft: 0,
  },
  btnWrap: {flexDirection: 'row', flexGrow: 1, flexShrink: 1, flexBasis: 0, justifyContent: 'space-around'},
  contact: {
    textAlign: 'center',
    fontSize: 16,
    color: '#fff',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0,
    marginRight: 20,
    marginBottom: 0,
    marginLeft: 20,
    width: 100,
    fontWeight: 'bold',
    lineHeight: 40,
  },
  btn: {
    width: 100,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0,
    marginRight: 20,
    marginBottom: 0,
    marginLeft: 20,
    color: '#FFFFFF',
    lineHeight: 40,
  },
}
