module.exports = {
  bg: {backgroundColor: '#f7f7f7'},
  header: {
    marginTop: 14,
    marginRight: 14,
    marginBottom: 14,
    marginLeft: 14,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    position: 'relative',
  },
  icon: {
    paddingTop: 3,
    paddingRight: 6,
    paddingBottom: 3,
    paddingLeft: 6,
    position: 'absolute',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 0,
  },
  mineHeader: {
    paddingTop: 14,
    paddingRight: 0,
    paddingBottom: 14,
    paddingLeft: 0,
    color: '#3A3A3A',
    fontSize: 14,
    fontWeight: '500',
  },
  cardHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  menuPoint: {color: '#9E9E9E', flexDirection: 'row', alignItems: 'center', fontSize: 14},
  scanWrap: {alignItems: 'center', marginTop: 200, display: 'flex', flexDirection: 'column'},
  scanIcon: {color: '#de423b', marginTop: 20, fontSize: 100},
  goodsName: {color: '#3A3A3A', textAlign: 'center', marginBottom: 24, fontSize: 18},
  btnBox: {position: 'absolute', bottom: 0, backgroundColor: '#FFFFFF', width: '100%'},
  btn: {
    textAlign: 'center',
    lineHeight: 50,
    color: '#FFFFFF',
    fontSize: 16,
    backgroundColor: '#E73A32',
    borderRadius: 6,
    marginTop: 14,
    marginRight: 50,
    marginBottom: 14,
    marginLeft: 50,
  },
  goodsTip: {color: '#3A3A3A', marginTop: 10, fontSize: 14, marginBottom: 30},
  goodsInfo: {fontSize: 14, color: '#909399', marginBottom: 5},
  iconText: {fontSize: 14, fontWeight: '400', color: '#FFFFFF', lineHeight: 18},
  leftTitle: {color: '#333'},
  image: {backgroundColor: '#f6f7f6', width: 80, borderRadius: 4, height: 80},
  right: {width: '100%', paddingTop: 0, paddingRight: 85, paddingBottom: 0, paddingLeft: 14},
  eachItem: {paddingTop: 10, paddingBottom: 10, width: '100%'},
  productSpec: {
    width: '80%',
    marginTop: 5,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: '#9E9E9E',
    fontSize: 13,
  },
  priceInfo: {
    width: '100%',
    paddingBottom: 20,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  createdTime: {color: '#9E9E9E', fontSize: 13},
  totalInfo: {color: '#3B3B3B', fontSize: 12, marginRight: 5},
  totalInfo1: {color: '#3B3B3B', fontSize: 12},
  eachPrice: {textAlign: 'right', marginLeft: 10, color: '#222222'},
  eachTitle: {width: '80%', fontSize: 14, color: '#222222'},
  statusLabel: {position: 'absolute', textAlign: 'right', width: '100%'},
  statusContext: {color: '#ff6f72', fontSize: 16},
  name: {flexDirection: 'row', alignItems: 'center'},
  itemInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 5,
    paddingRight: 0,
    paddingBottom: 5,
    paddingLeft: 0,
  },
  textInput: {
    width: '100%',
    paddingTop: 0,
    paddingRight: 14,
    paddingBottom: 0,
    paddingLeft: 28,
    backgroundColor: '#f6f7f9',
    borderRadius: 14,
  },
  textInputBox: {
    paddingTop: 12,
    paddingRight: 14,
    paddingBottom: 12,
    paddingLeft: 14,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
  },
  nameText: {color: '#222222', fontSize: 16, fontWeight: 'bold'},
  headerWrapper: {width: '100%', paddingTop: 4, position: 'relative', paddingBottom: 10},
  likeBtn: {
    marginRight: 10,
    marginBottom: 10,
    paddingTop: 6,
    paddingRight: 8,
    paddingBottom: 6,
    paddingLeft: 8,
    borderWidth: 1,
    borderColor: '#eee',
    borderStyle: 'solid',
  },
  like: {color: '#3A3A3A', textAlign: 'center', fontSize: 12},
  buyAgain: {textAlign: 'center', fontSize: 12, color: '#ff585e'},
  buyAgainBtn: {
    marginBottom: 4,
    marginRight: 8,
    paddingTop: 6,
    paddingRight: 8,
    paddingBottom: 6,
    paddingLeft: 8,
    borderWidth: 1,
    borderColor: '#ff585e',
    borderStyle: 'solid',
  },
  footer: {textAlign: 'right', paddingTop: 20, width: '100%', paddingBottom: 10},
  payInfo: {
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 18,
    paddingLeft: 10,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  overlay: {position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, zIndex: 100},
  showMenuTitle: {
    top: 0,
    zIndex: 101,
    color: '#3A3A3A',
    position: 'absolute',
    backgroundColor: '#fff',
    lineHeight: 40,
    height: 40,
    fontSize: 16,
    fontWeight: 'bold',
    paddingLeft: 14,
  },
  itemBox: {flexDirection: 'row', flexWrap: 'wrap', paddingBottom: 20},
  userAvatar: {width: 30, height: 30, borderRadius: 15, marginRight: 10},
  itemWrap: {
    width: '19%',
    marginTop: 5,
    marginRight: '3%',
    marginBottom: 5,
    marginLeft: '3%',
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#eee',
  },
  itemWrapActive: {borderColor: '#90A96E', backgroundColor: 'rgba(144, 169, 110, 0.1)'},
  itemTitle: {fontSize: 12, lineHeight: 30, color: '#999'},
}
