module.exports = {
  input: {
    paddingTop: 0,
    paddingRight: 28,
    paddingBottom: 0,
    paddingLeft: 14,
    width: '100%',
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
  },
  goodsImage: {
    backgroundColor: '#FFFFFF',
    marginLeft: 10,
    marginTop: 10,
    borderRadius: 5,
    display: 'flex',
    flexGrow: 0,
    flexDirection: 'column',
    overflow: 'hidden',
  },
  goodsName: {color: '#3A3A3A'},
  minPrice: {fontSize: 18, marginRight: 8, color: '#E73A32'},
  originalPrice: {
    fontSize: 14,
    textDecorationLine: 'line-through',
    textDecorationColor: 'black',
    textDecorationStyle: 'solid',
    color: '#9a9a9a',
  },
  filterBar: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    flexWrap: 'wrap',
    minHeight: 36,
    paddingTop: 6,
    borderBottomColor: '#eee',
  },
  filterItem: {fontSize: 16, width: '20%', textAlign: 'center', color: '#3A3A3A'},
  categoryTag: {
    backgroundColor: '#edecec',
    fontSize: 14,
    paddingTop: 2,
    paddingRight: 6,
    paddingBottom: 2,
    paddingLeft: 6,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: 14,
    marginBottom: 12,
    alignSelf: 'flex-start',
    lineHeight: 20,
    overflow: 'hidden',
  },
  itemImageTitle: {
    fontSize: 16,
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 4,
    textShadowColor: '#333',
    color: '#FFFFFF',
  },
  mockSearch: {
    maxWidth: '100%',
    height: 34,
    borderRadius: 16,
    backgroundColor: '#f3f3f3',
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 10,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  categoryText: {
    marginRight: 5,
    marginBottom: 5,
    paddingTop: 5,
    paddingRight: 5,
    paddingBottom: 5,
    paddingLeft: 5,
    borderRadius: 4,
  },
  active: {backgroundColor: '#feeeed', color: '#f03b3a'},
  mockSearchBlock: {
    width: '100%',
    height: 34,
    borderRadius: 16,
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 10,
  },
  mockIcon: {color: '#ababab', lineHeight: 34},
  mockTitle: {paddingLeft: 10, color: '#9E9E9E', lineHeight: 34},
  mockValue: {
    height: 26,
    overflow: 'hidden',
    lineHeight: 26,
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 10,
    marginTop: 4,
    marginLeft: 10,
  },
}
