module.exports = {
  pageBox: {backgroundColor: '#f8f8f8', height: '100%'},
  avatar: {width: 56, height: 56, borderRadius: 28},
  icon: {bottom: -9, width: 36, height: 36, position: 'absolute'},
  vip: {width: 65, height: 27},
  progressBox: {
    width: '70%',
    backgroundColor: '#72e5be',
    borderRadius: 10,
    borderWidth: 1,
    height: 4,
    borderColor: '#72e5be',
    position: 'relative',
    overflow: 'hidden',
    marginTop: 31,
  },
  progressItem: {position: 'absolute', height: 10, left: 0, backgroundColor: '#ffffff'},
  item: {borderRadius: 5, marginTop: 20, marginRight: 15, marginBottom: 0, marginLeft: 15},
  imageBox: {
    flexDirection: 'row',
    paddingTop: 0,
    paddingRight: 13,
    paddingBottom: 0,
    paddingLeft: 13,
    alignItems: 'center',
  },
  avatarBox: {position: 'relative'},
  infoWrap: {marginLeft: 15},
  name: {fontSize: 18, fontWeight: '500', color: '#3A3A3A', lineHeight: 24},
  level: {fontSize: 13, fontWeight: '400', color: '#666666', lineHeight: 24},
  levelLabel: {
    left: 0,
    top: 14,
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    paddingTop: 0,
    paddingRight: 10,
    paddingBottom: 0,
    paddingLeft: 10,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 11,
    borderBottomRightRadius: 11,
    borderBottomLeftRadius: 0,
  },
  levelLabelText: {fontSize: 11, fontWeight: '400', color: '#f7fdfc', lineHeight: 22},
  vipIcon: {right: 25, top: 25, position: 'absolute'},
  levelWrap: {marginTop: 35, fontSize: 35, fontWeight: 'bold', minHeight: 35, color: '#FEFEFE'},
  termBox: {
    position: 'relative',
    marginTop: 15,
    height: 165,
    borderRadius: 15,
    marginBottom: 15,
    paddingTop: 25,
    paddingRight: 25,
    paddingBottom: 0,
    paddingLeft: 20,
  },
  levelNow: {textAlign: 'center', fontSize: 16, fontWeight: '500', color: '#FBCEA5', lineHeight: 44},
  conditions: {
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '400',
    color: '#3A3A3A',
    lineHeight: 16,
    marginBottom: 15,
  },
  ruleImage: {marginTop: 20, width: '100%'},
  itemWrap: {
    marginTop: 15,
    marginRight: 0,
    marginBottom: 15,
    marginLeft: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    paddingTop: 20,
    paddingRight: 22,
    paddingBottom: 20,
    paddingLeft: 22,
  },
  ruleBox: {marginTop: 16, paddingTop: 0, paddingRight: 20, paddingBottom: 0, paddingLeft: 20},
  ruleItem: {flexDirection: 'row', marginTop: 20, alignItems: 'flex-start'},
  right: {marginLeft: 10},
  labelWrap: {fontSize: 13, fontWeight: '500', color: '#3A3A3A'},
  textWrap: {fontSize: 14, color: '#666666', lineHeight: 28},
  title: {textAlign: 'center', fontSize: 20, fontWeight: 'bold', color: '#3A3A3A'},
  patent: {flexDirection: 'row', flexWrap: 'wrap', width: '100%'},
  patentItem: {marginTop: 16, width: '20%', flexDirection: 'column', alignItems: 'center', textAlign: 'center'},
  label: {fontSize: 14, fontWeight: '400', color: '#3A3A3A', marginTop: 12, lineHeight: 20, textAlign: 'center'},
  btnBottomWrap: {width: '100%', flexDirection: 'row', position: 'absolute', bottom: 0},
  btnWrap: {
    textAlign: 'center',
    flex: 1,
    marginTop: 20,
    marginRight: 10,
    marginBottom: 20,
    marginLeft: 10,
    borderRadius: 25,
  },
  btnBottom: {fontSize: 16, lineHeight: 50, color: '#fff', textAlign: 'center', fontWeight: '500'},
  partnerExpire: {marginTop: 20, color: 'white'},
  zone: {marginTop: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  zoneItem: {
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 11,
    paddingRight: 8,
    paddingBottom: 11,
    paddingLeft: 8,
    borderRadius: 10,
    position: 'relative',
  },
  tip: {textAlign: 'center', marginTop: 5, fontSize: 11, fontWeight: '400', color: '#898989', lineHeight: 16},
  'right-item': {position: 'absolute', right: 8},
  btn: {
    lineHeight: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    borderStyle: 'solid',
    fontSize: 11,
    fontWeight: '400',
    color: '#3A3A3A',
    overflow: 'hidden',
    paddingTop: 0,
    paddingRight: 6,
    paddingBottom: 0,
    paddingLeft: 6,
  },
  color1: {backgroundColor: '#FFE2A7'},
  color2: {backgroundColor: '#FFDCCA'},
}
