const map = {
  '/pages/home/index': 'Home',
  '/pages/home/commentList': 'CommentList',
  '/pages/home/flashSale': 'FlashSale',
  '/pages/home/bargain': 'Bargain',
  '/pages/home/productDetail': 'ProductDetail',
  '/pages/home/productList': 'ProductList',
  '/pages/home/confirmOrder': 'ConfirmOrder',
  '/pages/packageOne/track': 'Track',
  '/pages/mine/logistics': 'Logistics',
  '/pages/mine/logisticsTrace': 'LogisticsTrace',
  '/pages/packageFour/afterSaleList': 'AfterSaleList',
  '/pages/packageFour/afterSale': 'AfterSale',
  '/pages/packageFour/afterSaleSelect': 'AfterSaleSelect',
  '/pages/packageOne/addressList': 'AddressList',
  '/pages/packageOne/phone': 'Phone',
  '/pages/auth/login': 'Login',
  '/pages/auth/register': 'Register',
  '/pages/auth/forgetPassword': 'ForgetPassword',
  '/pages/mine/index': 'Mine',
  '/pages/shop/index': 'Shop',
  //@
  '/pages/recommend/index': 'RecommendIndex',
  '/pages/mine/orderList': 'OrderList',
  '/pages/mine/shopOrderList': 'ShopOrderList',
  '/pages/mine/orderDetail': 'OrderDetail',
  '/pages/packageOne/config': 'Config',
  '/pages/mine/comment': 'Comment',
  '/pages/packageOne/idCard': 'IdCard',
  '/pages/packageOne/collection': 'Collection',
  '/pages/packageTwo/wallet': 'Wallet',
  '/pages/home/activitySpuDetail': 'ActivitySpuDetail',
  //@
  '/pages/mine/alipay': 'Alipay',
  '/pages/packageFour/videoList': 'VideoList',
  '/pages/mine/videoList': 'VideoList',
  '/pages/packageFour/videoDetail': 'VideoDetail',
  '/pages/mine/videoDetail': 'VideoDetail',
  '/pages/article': 'Article',
  '/pages/packageOne/address': 'EditAddress',
  '/pages/mine/edit/phone': 'EditPhone',
  '/pages/packageOne/nickname': 'EditNickname',
  '/pages/mine/edit/avatar': 'EditAvatar',
  '/pages/packageTwo/bankCard': 'EditBankCard',
  '/pages/packageOne/help': 'Help',
  '/pages/auth/wechatRegister': 'WechatRegister',
  '/pages/category/index': 'Category',
  '/pages/home/packageList': 'PackageList',
  '/pages/packageTwo/friend': 'Friend',
  '/pages/packageTwo/commission': 'Commission',
  '/pages/mine/coupon': 'Coupon',
  '/pages/home/couponList': 'CouponList',
  '/pages/home/packageDetail': 'PackageDetail',
  '/pages/packageOne/invoiceApply': 'InvoiceApply',
  '/pages/packageOne/invoiceAccountEdit': 'InvoiceAccountEdit',
  '/pages/packageOne/invoiceAccountList': 'InvoiceAccountList',
  '/pages/packageOne/coinProductList': 'CoinProductList',
  '/pages/packageOne/coinProductDetail': 'CoinProductDetail',
  '/pages/packageOne/coinOrderList': 'CoinOrderList',
  '/pages/packageThree/store': 'Store',
  '/pages/home/shopList': 'ShopList',
  '/pages/customPage': 'CustomPage',
  '/pages/home/photoList': 'PhotoList',
  '/pages/packageOne/history': 'History',
  '/pages/packageOne/chat': 'Chat',
  '/pages/home/mall': 'Mall',
  '/pages/packageOne/regionalPage': 'RegionalPage',
  '/pages/category/free-mall': 'FreeMall',
  '/pages/packageFour/free-mall': 'FreeMall',
  '/pages/category/browse': 'Browse',
  '/pages/packageTwo/cardPackage': 'CardPackage',
  '/pages/live/index': 'Live',
  '/pages/packageTwo/zone': 'Zone',
  '/pages/packageFour/onePost': 'OnePost',
  '/pages/packageFour/selectFarm': 'SelectFarm',
  '/pages/mine/invite': 'Invite',
  '/pages/home/shopSpuDetail': 'ShopSpuDetail',
  '/pages/packageOne/promote': 'Promote',
  '/pages/packageFour/commissionMall': 'CommissionMall',
  // 暂未完成
  '/pages/packageFour/cow': 'Cow', //牧场
  '/pages/packageFour/tree': 'Tree', //果园
  '/pages/packageOne/customerService': 'CustomerService', //客服链接
}

export default map
