module.exports = {
  cardBox: {
    paddingTop: 20,
    paddingRight: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    marginTop: 0,
    marginRight: 14,
    marginBottom: 0,
    marginLeft: 14,
    backgroundColor: 'rgba(254, 104, 126, 0.7)',
    borderRadius: 6,
    borderWidth: 3,
    borderColor: 'rgba(254, 136, 153, 0.4)',
  },
  topWrap: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  status: {fontSize: 13, fontWeight: '400', color: '#FFFFFF', lineHeight: 16},
  identityLabel: {fontSize: 14, fontWeight: '400', color: '#FFFFFF', lineHeight: 17},
  recordLabel: {fontSize: 14, fontWeight: '400', color: '#FFFFFF', lineHeight: 17},
  cardWrap: {marginTop: 24, color: '#3A3A3A', borderRadius: 15},
  local: {fontSize: 14, fontWeight: '400', color: '#FFFFFF', lineHeight: 17},
  balance: {flexDirection: 'row', alignItems: 'center', marginLeft: 14},
  balanceLabel: {fontSize: 12, fontWeight: '400', color: '#9E9E9E', lineHeight: 17},
  balanceText: {marginLeft: 6, fontSize: 20, fontWeight: '400', color: '#3A3A3A', lineHeight: 28},
  typeValue: {
    height: 50,
    marginTop: 0,
    marginRight: 20,
    marginBottom: 0,
    marginLeft: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceText: {fontSize: 28, fontWeight: '500', color: '#FFFFFF', lineHeight: 40},
  qrCode: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    right: -16,
    backgroundColor: '#fff',
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 16,
    borderTopLeftRadius: 17,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 17,
  },
  qrCodeText: {lineHeight: 34, fontSize: 13, fontWeight: '400', color: '#3A3A3A'},
  contentTitle: {
    marginTop: 20,
    marginRight: 14,
    marginBottom: 10,
    marginLeft: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  contentTitleLine: {height: 17, width: 4, borderRadius: 2, backgroundColor: '#FF2050', marginRight: 10},
  contentTitleText: {fontSize: 17, fontWeight: '500', color: '#3A3A3A', lineHeight: 24},
  unit: {fontSize: 25},
  revenueWrap: {
    marginTop: 14,
    marginRight: 0,
    marginBottom: 14,
    marginLeft: 0,
    backgroundColor: '#fff',
    borderRadius: 15,
    paddingTop: 10,
    paddingRight: 10,
    paddingBottom: 10,
    paddingLeft: 10,
  },
  revenueHead: {
    flexDirection: 'row',
    textAlign: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F2F2F2',
    borderRadius: 4,
  },
  revenueHeadText: {fontSize: 14, fontWeight: '500', lineHeight: 40, color: '#3A3A3A'},
  revenueItem: {
    paddingTop: 15,
    paddingRight: 0,
    paddingBottom: 15,
    paddingLeft: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  revenueItemText: {fontSize: 13, fontWeight: '400', color: '#3A3A3A'},
  summary: {
    flexDirection: 'row',
    marginTop: 0,
    marginRight: 20,
    marginBottom: 0,
    marginLeft: 20,
    backgroundColor: '#fff',
    borderRadius: 15,
    paddingTop: 18,
    paddingRight: 0,
    paddingBottom: 19,
    paddingLeft: 0,
  },
  emptyText: {
    marginTop: 20,
    marginRight: 0,
    marginBottom: 20,
    marginLeft: 0,
    textAlign: 'center',
    fontSize: 16,
    color: '#cdcdcd',
  },
  summaryAmount: {width: '50%', flexDirection: 'column', alignItems: 'center', borderRight: '1px solid #EEEEEE'},
  summaryIncome: {width: '50%', flexDirection: 'column', alignItems: 'center'},
  label: {fontSize: 12, fontWeight: '400', color: '#888888', lineHeight: 17},
  textWrap: {marginTop: 5, fontSize: 30, fontWeight: '600', color: '#3A3A3A', lineHeight: 31},
  icon: {fontWeight: '400', color: '#666666', fontSize: 14},
  wrap: {borderRadius: 10, marginTop: 10, marginRight: 14, marginBottom: 10, marginLeft: 14},
  amountBox: {marginTop: 20, flexDirection: 'row', justifyContent: 'space-between'},
  navRight: {paddingRight: 20, color: '#fff'},
  amountItem: {
    paddingTop: 20,
    paddingRight: 10,
    paddingBottom: 20,
    paddingLeft: 10,
    textAlign: 'center',
    backgroundColor: '#fff',
    borderRadius: 15,
  },
  spec: {color: '#3A3A3A', fontSize: 12, lineHeight: 20, textAlign: 'center'},
  price: {textAlign: 'center', marginTop: 6, fontSize: 20, color: '#0B1434', lineHeight: 30},
  compareBox: {marginTop: 6, fontSize: 12, fontWeight: '600'},
  compareBottomBox: {flexDirection: 'row', justifyContent: 'center', alignItems: 'center', backgroundColor: '#fff'},
  modalBox: {width: '80%', maxHeight: '60%', zIndex: 1, backgroundColor: '#fff', borderRadius: 10},
  titleBox: {paddingTop: 10, paddingRight: 0, paddingBottom: 10, paddingLeft: 0},
  titleText: {textAlign: 'center', fontSize: 21, fontWeight: '400', color: '#3A3A3A'},
  contentBox: {
    position: 'absolute',
    top: 80,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    marginTop: 'auto',
    marginRight: 'auto',
    marginBottom: 'auto',
    marginLeft: 'auto',
    textAlign: 'center',
  },
  bottomModalBox: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
    backgroundColor: '#fff',
    width: '100%',
    position: 'absolute',
    bottom: 0,
  },
  shareBox: {flexDirection: 'row', paddingTop: 0, paddingRight: 20, paddingBottom: 10, paddingLeft: 20},
  shareItem: {width: '25%', flexDirection: 'column', alignItems: 'center'},
  shareText: {textAlign: 'center', marginTop: 10},
}
