module.exports = {
  pageBox: {height: '100%', backgroundColor: '#f7f7f7'},
  searchBox: {backgroundColor: '#fff'},
  infoWrap: {fontSize: 16, color: '#3A3A3A'},
  renderItem: {
    marginTop: 14,
    marginRight: 14,
    marginBottom: 14,
    marginLeft: 14,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderBottom: '1px solid #eee',
    paddingTop: 14,
    paddingRight: 14,
    paddingBottom: 14,
    paddingLeft: 14,
  },
  images: {marginTop: 10, flexDirection: 'row', flexWrap: 'wrap'},
  footer: {
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 10,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: 14,
  },
  content: {fontSize: 14, marginTop: 10, color: '#E73A32'},
  shareArea: {flexDirection: 'row', alignItems: 'center'},
}
